- packages/demo/e2e/basic.test.ts
- packages/demo/index.html
- packages/demo/misc/vercel/.vc-config.json
- packages/demo/misc/vercel/build.sh
- packages/demo/package.json
- packages/demo/src/client/index.tsx
- packages/demo/src/server/adapter-connect.ts
- packages/demo/src/server/adapter-vercel-edge.ts
- packages/demo/src/server/index.ts
- packages/demo/src/server/render-routes.tsx
- packages/demo/vite.config.ts
- pnpm-lock.yaml
- a part of https://github.com/hi-ogawa/vite-plugins/issues/10
- https://github.com/unocss/unocss/issues/1961
- very oddly this happens on initial render and it stops, for example, when triggering legitimate HMR by modifying some component.
- https://github.com/hi-ogawa/vite-plugins/pull/12
- fixed in https://github.com/hi-ogawa/vite-plugins/pull/11/commits/02a20c59ea9047f25219de084b3750a45f66dc7c
- fine to give up edge and just use nodejs serverless. maybe move code to `demo-ssr`?
- remix runs on edge so there has to be a way to do it though?
- well bundle size already got to 1.3mb so cannot push it to cloudflare anyway...
- fixed in https://github.com/hi-ogawa/vite-plugins/pull/11/commits/3897fbeb8b0a3a5c60b823d79829db308075f64e
> fea: integrate react-router ssr

- README.md
- packages/demo/e2e/basic.test.ts
- packages/demo/src/routes/server-data-utils.ts
- packages/demo/src/routes/server-data.page.server.tsx
- packages/demo/src/routes/server-data.page.tsx
- packages/demo/src/server/index.ts
- packages/demo/src/server/render-routes.tsx
- packages/demo/src/server/request-context.d.ts
- packages/vite-glob-routes/src/index.ts
- packages/vite-glob-routes/src/react-router-utils.test.ts
- packages/vite-glob-routes/src/react-router-utils.ts
- packages/vite-glob-routes/src/react-router.ts
- packages/vite-glob-routes/src/virtual.d.ts
- merge base https://github.com/hi-ogawa/vite-plugins/pull/17
- employ vite-plugin-ssr like `*.page.server.tsx` for server code
- setup react-router `loader` only during SSR so that it could be used to mutate queryClient itself to provide data implicitly
> feat: integrate react-router loader on SSR

- packages/demo/src/routes/client-redirect/[id].page.tsx
- packages/demo/src/routes/client-redirect/index.page.tsx
- packages/demo/src/routes/layout.tsx
- packages/demo/src/routes/server-redirect/[id].page.server.tsx
- packages/demo/src/routes/server-redirect/[id].page.tsx
- packages/demo/src/routes/server-redirect/index.page.tsx
- packages/demo/src/utils/misc.ts
- merge base https://github.com/hi-ogawa/vite-plugins/pull/17
- part 3 of https://github.com/hi-ogawa/vite-plugins/issues/10
we can throw "redirection response" in react-router's loader, so the bare minimum form of server side redirection is already possible.
> feat: support server redirection

- packages/demo/e2e/basic.test.ts
- packages/demo/misc/vercel/build.sh
- packages/demo/src/routes/error.page.tsx
- packages/demo/src/routes/layout.tsx
- packages/demo/src/routes/subdir/layout.tsx
- packages/demo/src/routes/subdir/other.page.tsx
- packages/vite-glob-routes/src/index.ts
- packages/vite-glob-routes/src/react-router-utils.test.ts
- packages/vite-glob-routes/src/react-router-utils.ts
- packages/vite-glob-routes/src/virtual.d.ts
Simplifying route/page convention by adapting a whole `RouteObject` interface directly from react-router.
This allows using `ErrorBoundaray`, `handle` etc... already.
> feat(glob-routes): align with react-router API

- packages/demo/src/routes/server-redirect/[id].page.server.tsx
- packages/vite-glob-routes/src/index.ts
- packages/vite-glob-routes/src/react-router.ts
It seems client build is still seeing `*.page.server.tsx` code even when we guard glob import by `import.meta.env.SSR`:
https://github.com/hi-ogawa/vite-plugins/blob/eab55ae4f5e6fad50c6bfd95e4862e383e43160b/packages/vite-glob-routes/src/index.ts#L52-L59
```
$ pnpm build
...
vite v4.3.9 building for production...
transforming (25) ../vite-glob-routes/dist/chunk-YXB3VE22.js[plugin:vite:resolve] Module "node:crypto" has been externalized for browser compatibility, imported by "/home/hiroshi/code/personal/vite-plugins/packages/demo/src/routes/server-redirect/[id].page.server.tsx". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 129 modules transformed.
dist/client/index.html                   2.06 kB │ gzip:  1.22 kB …
```
> fix(glob-routes): tree shake server code from client

- packages/demo/e2e/basic.test.ts
- packages/demo/src/routes/error.page.tsx
- packages/demo/src/server/index.tsx
- packages/vite-glob-routes/src/react-router-helper-server.ts
- packages/vite-glob-routes/src/react-router.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/58
- supersedes https://github.com/hi-ogawa/vite-plugins/pull/56
~It can be implemented in the app-side, but hopefully there's a way to abstract this logic to glob-routes plugin?~
It's only a matter of modifying `StaticContextHandler.statusCode/errors` so it looks fine without too much abstraction.
> feat(demo): two pass render to trigger ErrorBoundary on SSR error

- packages/demo/src/client/index.tsx
- packages/demo/src/server/index.tsx
- packages/vite-glob-routes/src/hattip.ts
- packages/vite-glob-routes/src/index.ts
- packages/vite-glob-routes/src/react-router.ts
- packages/vite-glob-routes/src/virtual.d.ts
- packages/vite-glob-routes/tsup.config.ts
For clarity, renaming exports to be
```
globPageRoutesClient
globPageRoutesClientLazy
globPageRoutesServer
```
> refactor(glob-routes): renaming exports

- packages/demo/src/routes/layout.tsx
- packages/vite-glob-routes/src/react-router-helper-client.ts
- packages/vite-glob-routes/src/react-router-helper-shared.ts
- packages/vite-glob-routes/src/react-router.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/40
~Idea is something like this, but the boundary of plugin/app is becoming messy.
Somehow I'm resisting again introducing helper component/hook in the plugin (e.g. context, hook).
Especially we need a clean way to deal with `ExtraRouterInfo` global.~
Ended up introducing honest `ClinetGlobal`, which makes it easy to add more client helpers.
> feat: support page prefetching

- package.json
- packages/demo/misc/vercel/build.sh
- packages/demo/package.json
- packages/demo/playwright.config.ts
> chore: set `"type": "module"`

- .changeset/rich-lamps-turn.md
- examples/spa/src/client/index.tsx
- examples/ssr/src/client/index.tsx
- packages/demo/playwright.config.ts
- packages/demo/src/client/index.tsx
- packages/vite-glob-routes/package.json
- packages/vite-glob-routes/src/react-router/client-eager.ts
- packages/vite-glob-routes/src/react-router/client.ts
- packages/vite-glob-routes/tsup.config.ts
Having both eager/lazy glob imports in one file was tricky to debug sometime, so let's just split it for explicit-ness:
https://github.com/hi-ogawa/vite-plugins/blob/60eb4903177c4fab942ebe6609c51d32df4cd216/packages/vite-glob-routes/src/react-router/client.ts#L1-L2
> refactor(glob-routes)!: separate non-lazy client routes

- packages/demo/package.json
- packages/demo/src/routes/layout.tsx
- packages/demo/vite.config.ts
- packages/vite-null-export/README.md
- packages/vite-null-export/package.json
- packages/vite-null-export/src/index.ts
- packages/vite-null-export/tsconfig.json
- packages/vite-null-export/tsup.config.ts
- pnpm-lock.yaml
Making a dedicated package for
- https://github.com/hi-ogawa/cloudflare-workers-example/blob/98558796ac9330d38df86b234ca5f1971ad563d4/vite.config.ts#L39
- emptify, nullify, fake
- module, exports
- https://github.com/vikejs/vike/issues/744
- similar but this is to guard against unintended usage
- https://github.com/remix-run/remix/pull/7590
- probably their vite plugin would require similar thing?
> feat: create `vite-null-export` package

- examples/spa/src/routes/layout.tsx
- examples/spa/src/routes/pokemon/layout.tsx
- examples/spa/tsconfig.json
- examples/ssr/src/routes/layout.tsx
- examples/ssr/tsconfig.json
- packages/demo/src/routes/error.page.tsx
- packages/demo/src/routes/server-redirect/[id].page.tsx
- packages/demo/tsconfig.json
Technically `@vitejs/plugin-react` shouldn't be necessary since vite/esbuild can transpile tsx out-of-the-box as long as tsconfig is setup properly.
> chore: add react jsx runtime in tsconfig

- packages/vite-node-miniflare/examples/react-router/vite.config.ts
- packages/vite-node-miniflare/examples/react/vite.config.ts
- packages/vite-node-miniflare/src/server/plugin.ts
- packages/vite-node-miniflare/src/server/pre-bundle/plugin.ts
- packages/vite-node-miniflare/src/server/pre-bundle/utils.ts
- part of https://github.com/hi-ogawa/vite-plugins/issues/127
> feat(vite-node-miniflare): cache pre-bundle

- packages/vite-node-miniflare/src/client/polyfills/node-url.ts
- packages/vite-node-miniflare/src/server/vite-node.ts
After investigation in https://github.com/hi-ogawa/vite-plugins/pull/134, it turned out Workerd throws when `new URL(file://something-relative)` depending on `compatibilityDate`.
Probably it should be fixed on `vite-node-miniflare` side.
> fix(vite-node-miniflare): fix `pathToFileURL` for virtual module

- .changeset/nasty-llamas-glow.md
- packages/vite-node-miniflare/examples/basic/e2e/basic.test.ts
- packages/vite-node-miniflare/examples/basic/src/app.tsx
- packages/vite-node-miniflare/examples/basic/src/crash-dep.ts
- packages/vite-node-miniflare/examples/basic/src/crash.tsx
- packages/vite-node-miniflare/package.json
- packages/vite-node-miniflare/src/client/polyfills/node-path.ts
- packages/vite-node-miniflare/src/client/polyfills/node-vm.ts
- packages/vite-node-miniflare/src/client/vite-node.ts
Part of https://github.com/hi-ogawa/vite-plugins/issues/127
It turns out Workerd's `eval` already supports `name` option for stacktrace!
- https://github.com/cloudflare/workerd/pull/1338
> feat(vite-node-miniflare): support error stack sourcemap

- packages/demo/package.json
- packages/demo/playwright.config.ts
- packages/demo/vite.config.ts
- pnpm-lock.yaml
- closes https://github.com/hi-ogawa/vite-plugins/issues/99
Looks good?
https://github.com/hi-ogawa/vite-plugins/actions/runs/7327401800/job/19954230973#step:11:11
```
Running 24 tests using 2 workers
···×××±·±··················
Slow test file: [chromium] › basic.test.ts (44.5s)
Slow test file: [chromium] › session.test.ts (36.9s)
Consider splitting slow test files to speed up parallel execution
2 flaky
[chromium] › basic.test.ts:5:1 › basic ─────────────────────────────────────────────────────────
[chromium] › session.test.ts:5:3 › session › basic ─────────────────────────────────────────────
22 passed (48.5s)
```
No retry!
https://github.com/hi-ogawa/vite-plugins/actions/runs/7334364661/job/19970952135#step:11:11
```
Running 24 tests using 2 workers
························
24 passed …
```
> fix(demo): set `optimizeDeps` to avoid late discovery

- packages/vite-node-miniflare/examples/basic/package.json
- packages/vite-node-miniflare/examples/basic/vite.config.ts
- packages/vite-node-miniflare/src/client/worker-entry.ts
- packages/vite-node-miniflare/src/server/plugin.ts
- pnpm-lock.yaml
Still holding off from setting up birpc. For now, let's refactor uni-directional RPC approach as `HMRRuntimeConnection` implementation.
> refactor(vite-node-miniflare): simplify `HMRConnection` implementation

- packages/vite-node-miniflare/package.json
- packages/vite-node-miniflare/src/client/worker-entry-script.ts
- packages/vite-node-miniflare/src/server/plugin.ts
- packages/vite-node-miniflare/tsup.config.ts
Previously we were defining `__DEFINE_WORKER_ENTRY_SCRIPT` to pass worker entry as raw string js, but this doesn't seem necessary at all.
> refactor(vite-node-miniflare): load worker entry by file path

- packages/vite-node-miniflare/package.json
- packages/vite-node-miniflare/src/client/worker-entry.ts
- packages/vite-node-miniflare/src/server/plugin.ts
- packages/vite-node-miniflare/src/shared.ts
- supersedes https://github.com/hi-ogawa/vite-plugins/pull/169
- supersedes https://github.com/hi-ogawa/vite-plugins/pull/168
This PR adds http rpc endpoint on Workerd side, so that ViteDevServer can send `onUpdate` in real time.
> feat(vite-node-miniflare): setup client RPC for hmr

- packages/react-server/examples/basic/src/entry-rsc.tsx
- packages/react-server/examples/basic/src/entry-server.tsx
- packages/react-server/examples/basic/src/lib/csr.tsx
- packages/react-server/examples/basic/src/lib/rsc.tsx
- packages/react-server/examples/basic/src/lib/shared.tsx
- packages/react-server/examples/basic/src/lib/ssr.tsx
Since we can tweak `id` from `moduleMap`, RSC render doesn't need to care about `renderId` trick.
Now this trick is self-contained in SSR side.
> refactor(react-server): simplify dev ssr module cache invalidation

- packages/react-server/README.md
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/action/action.tsx
- packages/react-server/examples/basic/src/routes/test/action/client.tsx
- packages/react-server/examples/basic/src/routes/test/action/page.tsx
- packages/react-server/package.json
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/entry/types-global.d.ts
- packages/react-server/src/lib/debug.ts
- packages/react-server/src/lib/shared.tsx
- packages/react-server/src/lib/types.ts
I'm not sure what's `encodeReply/decodeReply` is doing, but it looks like I can ditch them for now.
I simplified action id encoding to support progressive enhancement by manually injecting `$ACTION_ID_` via `$$FORM_ACTION`.
Probably this works only because there's no magical `bind`, but I guess it's fine for now.
related?
- https://github.com/facebook/react/pull/26774
> feat(react-server): progressive enhancement

- .github/workflows/ci.yml
- .npmrc
- package.json
- packages/react-server/examples/starter/package.json
- pnpm-lock.yaml
> chore(react-server): use "latest" for example dependencies

- packages/react-server/examples/basic/deps/server-component/index.d.ts
- packages/react-server/examples/basic/deps/server-component/index.js
- packages/react-server/examples/basic/deps/server-component/package.json
- packages/react-server/examples/basic/deps/use-client/index.js
- packages/react-server/examples/basic/deps/use-client/package.json
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/routes/test/deps/page.tsx
- pnpm-lock.yaml
It looks like `bright` uses `fs`. Dev is working but failing on build with `noExternal: true`.
For now, let's uses fixture deps with `file:...` protocol.
> test(react-server): test 3rd party server component library

- packages/react-server/package.json
- packages/react-server/src/plugin/index.ts
- pnpm-lock.yaml
For reproducibility, we probably should just hash it.
<details><summary>before</summary>
</details>
<details><summary>after</summary>
</details>
TODO
> feat(react-server): obfuscate reference id on production

- packages/react-server/examples/basic/src/components/nav-menu.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
Using `grid-cols-2` to organize a little:
> chore(examples): tweak `NavMenu`

- packages/react-server/package.json
- packages/vite-glob-routes/package.json
- packages/vite-import-dev-server/package.json
- packages/vite-node-miniflare/package.json
- packages/vite-null-export/package.json
- packages/vite-plugin-simple-hmr/package.json
- packages/vite-plugin-ssr-middleware/package.json
- pnpm-lock.yaml
Probably we can move `"vite"` deps to root?
> chore(deps): simplify dev deps

- packages/react-server/package.json
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/lib/global.ts
- packages/react-server/src/lib/router.tsx
- packages/react-server/src/plugin/index.ts
- packages/react-server/tsup.config.ts
- https://github.com/vitejs/vite/pull/16068
- https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name
Since Vite 5.2.0, we can use self-reference import and finally we can remove a few internal hacks.
---
Maybe not... actually external "use client" library such as this:
https://github.com/hi-ogawa/vite-plugins/blob/f972e5e376f4f365f438c9c1566bf9a96b508588/packages/react-server/examples/basic/deps/use-client/index.js#L1-L7
will be transformed to this during RSC build:
```ts
import { createClientReference } from "@hiogawa/react-server/server-internal";
export const TestDepUseClient = createClientReference("...")
```
but `@hiogawa/react-server` is not necessary visible depending on monorepo `node_modules` structure as seen in …
> refactor(react-server): use self-reference imports

- packages/react-server/package.json
- packages/react-server/src/plugin/index.ts
- I just silenced in `onwarn`, but maybe we can make quick transform to remove `"use client"` after `createClientReference` is taken care?
- No, this warning is not from RSC build since RSC build already removes `"use clinet"` when transforming it to `createClientReference`.
- why don't we see the same for `"use server"` for RSC build? Maybe warning happens only when build chunk's source has directive at the top? (client reference is already a separate dynamic import chunk)
> fix(react-server): silence false warning due to `use client`

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/package.json
- packages/react-server/src/lib/components/link.tsx
Started to checkout other client side routers. This one was really bugging me, so just a quick fix.
> fix(react-server): intercept only simple click on `Link`

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/action/_action.tsx
- packages/react-server/examples/basic/src/routes/test/action/_client.tsx
- packages/react-server/examples/basic/src/routes/test/action/page.tsx
- packages/react-server/examples/basic/tsconfig.json
It turns out `useFormStatus` is simply a react feature and it just works?
- https://react.dev/reference/react-dom/hooks/useFormStatus
> test(react-server): test `ReactDom.useFormStatus`

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/_client.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
Currently, everything is re-rendered on each RSC update, but it shouldn't be the case if we refine RSC update based on route tree?
> test(react-server): test client render count

- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
Knowing `Router` is a singleton, we can just skip `useContext` there.
> refactor(react-server): tweak context

- .github/workflows/ci.yml
Not sure why CI is not running in https://github.com/hi-ogawa/vite-plugins/pull/235. Maybe I need to enable this?
> ci: trigger ci on `pull_request`

- packages/vite-node-miniflare/examples/react-router/vite.config.ts
- packages/vite-node-miniflare/examples/remix/vite.config.ts
- packages/vite-node-miniflare/package.json
- packages/vite-node-miniflare/src/server/plugin.ts
It looks like `MiniflareOptions` union cannot infer when used contravariantly?
```ts
export type MiniflareOptions = SharedOptions &
(WorkerOptions | { workers: WorkerOptions[] });
```
https://github.com/cloudflare/workers-sdk/blob/d994066f255f6851759a055eac3b52a4aa4b83c3/packages/miniflare/src/index.ts#L134-L136
Pinning `MiniflareOptions & WorkerOptions` should help easier usage.
> fix(vite-node-miniflare): fix `miniflareOptions` typing

- packages/react-server/package.json
- packages/react-server/src/plugin/index.ts
I'm guessing this single flakiness is due to `react-dom` optimize deps reload https://github.com/hi-ogawa/vite-plugins/pull/209.
<details><summary>comment about old approach</summary>
Collecting local `"use client"` as deps optimization entries should help, but this actually cannot cover the cases where `"use client"` comes as external and directly imported to server component, for example:
https://github.com/hi-ogawa/vite-plugins/blob/561c68111c3c279438d920414582b315ff4948e2/packages/react-server/examples/basic/src/routes/test/deps/page.tsx#L3-L7
Implementing own deps scan for server routes `src/routes/**/*(page|layout).tsx` might be possible, but I guess it's fine for now. Or maybe we can just put all the routes like I did for Remix:
- https://github.com/hi-ogawa/ytsub-v3/pull/536 …
> feat(react-server): setup client `optimizeDeps.entries`

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/examples/basic/src/routes/test/session/_action.tsx
- packages/react-server/examples/basic/src/routes/test/session/layout.tsx
- packages/react-server/examples/basic/src/routes/test/session/page.tsx
- packages/react-server/examples/basic/src/routes/test/session/signin/page.tsx
- packages/react-server/examples/basic/src/routes/test/session/utils.ts
- packages/react-server/examples/basic/vite.config.ts
- packages/react-server/package.json
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/server-action/react-server.tsx
- packages/react-server/src/lib/client/error-boundary.tsx
- packages/react-server/src/lib/error.tsx
- packages/react-server/src/server.ts
- pnpm-lock.yaml
- supersedes https://github.com/hi-ogawa/vite-plugins/pull/253
Having access to `request` is obviously necessary (e.g. for `request.header.get("cookie")`), but I'm not sure about how `responseHeaders` mutation could be used for "successful" response as returning `set-cookie` for redirection error is already possible by https://github.com/hi-ogawa/vite-plugins/pull/253
> feat(react-server): action redirect headers and context

- packages/react-server/package.json
- packages/react-server/src/entry/server.tsx
I just realized something is wrong on stackblitz and maybe I made a typo `","` instead of `";"`.
<details><summary>before</summary>
</details>
---
Thank god, now it's back...
https://stackblitz.com/edit/github-dwdysf?file=package.json
<details><summary>after</summary>
</details>
> fix(react-server): fix html content-type

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/action/_action.tsx
- packages/react-server/examples/basic/src/routes/test/action/_client.tsx
- packages/react-server/examples/basic/src/routes/test/action/page.tsx
- packages/react-server/package.json
- packages/react-server/src/client.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/utils.tsx
- packages/react-server/src/features/server-action/client.tsx
- packages/react-server/src/features/server-action/react-server.tsx
- packages/react-server/src/lib/error.tsx
Probably I should start to look into official `useFormState/useActionState`, or can we get away with custom formData and server reference management?
<details><summary>Demo</summary>
</details>
- return action data in rsc stream and provide as react context
- ~probably can do similar to remix, handoff action data from server to client~
- uniform action stream handling for error case
> feat(react-server): action return value (implement `useActionData`)

- packages/react-server/README.md
- packages/react-server/examples/basic/src/routes/test/session/_action.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/server-action/react-server.tsx
- packages/react-server/src/server.ts
Sine we probably don't do the official action `bind`, we could just use `this: ActionContext` for our own thing.
> refactor(react-server): use `this: ActionContext`

- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/server-component/utils.tsx
There's one low-hanging refactoring and then it will probably easily allow layout invalidation from server action.
> refactor(react-server): layout invalidation on server

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/action/_action.tsx
- packages/react-server/examples/basic/src/routes/test/action/page.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/router/utils.tsx
- packages/react-server/src/features/server-action/react-server.tsx
- packages/react-server/src/features/server-component/utils.tsx
For https://github.com/hi-ogawa/react-server-demo-remix-tutorial
> feat(react-server): add `ActionContext.revalidate`

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/dynamic/layout.tsx
- packages/react-server/src/lib/router.tsx
Not sure where decoding should be applied. We should probably check with react router and tanstack.
- https://github.com/remix-run/react-router/pull/9477
- https://github.com/TanStack/router/commit/a2019034813bea2698e89ce4861dce0d5687a176
Looking at tanstack, just running `decodeURI` for `props.params` seems enough, which is also what I did in the demo
- https://github.com/hi-ogawa/react-server-demo-remix-tutorial/blob/5ee83567cb77b667f0417f19e1fde548e82e63b5/src/routes/contacts/%5BcontactId%5D/page.tsx#L7-L8
> fix(react-server): decode dynamic route params

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/error/layout.tsx
- packages/react-server/examples/basic/src/routes/test/error/page.tsx
- packages/react-server/examples/basic/src/routes/test/error/use-client/page.tsx
- packages/react-server/examples/basic/src/routes/test/error/use-server/page.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/entry/server.tsx
- follow up to https://github.com/hi-ogawa/react-server-demo-remix-tutorial/pull/1
Currently some common react server usage error (such as forgetting "use client", "use server", server/client props serialization) is hard to notice.
For now, having just `console.error` for unexpected errors should help DX.
- https://github.com/hi-ogawa/vite-plugins/pull/272
- or this should be enogh? https://github.com/hi-ogawa/vite-plugins/pull/274
> feat(react-server): log unexpected error

- packages/react-server/src/plugin/index.ts
- packages/react-server/tsup.config.ts
I'm still hesitant to land a large PR
- https://github.com/hi-ogawa/vite-plugins/pull/257
but, for starter, just preloading these two should be simple enough:
- `@hiogawa/react-server/client-internal`
- `/dist/rsc/client-references.js`
> fix(react-server): preload root js assets

- packages/react-server/examples/basic/e2e/basic.test.ts
- follow up to https://github.com/hi-ogawa/vite-plugins/pull/265
- related https://github.com/hi-ogawa/vite-environment-examples/pull/16
I thought this last step was broken, but it's actually fine, so probably the DX wouldn't be that bad after all.
The reason why https://github.com/hi-ogawa/vite-environment-examples/pull/16 is failing is simply because of rsc reload and client reload is happening at the same time.
> test(react-server): further more hmr tests

- packages/react-server/src/features/use-client/react-server.tsx
- packages/react-server/src/lib/types-env.d.ts
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/server-internal.ts
- cf. https://github.com/hi-ogawa/vite-environment-examples/pull/17
Let's test it here too since obviously we have more coverage here.
> refactor(react-server): use official `registerClientReference`

- packages/react-server/examples/basic/src/routes/test/error/hydration/page.tsx
- packages/react-server/examples/basic/src/routes/test/error/layout.tsx
Though client component ssr/csr mismatch is really unlikely in react server framework, I wanted to test this feature out:
- https://github.com/facebook/react/pull/28512
<details><summary>Show screenshots</summary>
</details>
It would be cool if it can be shown in vite error overlay by
- https://github.com/hi-ogawa/vite-plugins/pull/272
> test(react-server): test hydration mismatch error

- packages/error-overlay/CHANGELOG.md
- packages/error-overlay/package.json
- packages/error-overlay/src/index.ts
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/routes/test/error.tsx
- packages/react-server/examples/basic/vite.config.ts
- pnpm-lock.yaml
- follow up https://github.com/hi-ogawa/vite-plugins/pull/272
- supersedes https://github.com/hi-ogawa/vite-plugins/pull/274
Since some "errors" only show on in `console.error`, so they won't be automatically processed by `vitePluginErrorOverlay`.
Either we need to do:
- re-throw some errors inside react-server so it'll trigger unhandled error event.
- extend `vitePluginErrorOverlay` to be able to receive custom error from react-server 
- extend `vitePluginErrorOverlay` to handle `console.error` log by patching
- :heavy_check_mark: this seems robust enough and nicely covers react use cases out-of-the-box without changing anything on react-server integration.
It doesn't look like `hydrateRoot.onRecoverableError` tells about the error either.
> feat(error-overlay): collect errors from `console.error`

- packages/react-server/src/entry/react-server.tsx
See https://github.com/hi-ogawa/vite-environment-examples/blob/b134ae1704cbee96d1ed21e77b9f5f0f1e99b7ae/examples/react-server/src/features/server-action/react-server.ts#L22
This should be equivalent since dynamic import is transformed by Vite
> refactor(react-server): replace `ssrLoadModule` with `import`

- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/server-action/browser.tsx
- packages/react-server/src/features/server-action/client.tsx
- packages/react-server/src/features/server-action/react-server.tsx
- packages/react-server/src/features/use-client/browser.tsx
- packages/react-server/src/features/use-client/server.tsx
- packages/react-server/src/lib/global.ts
- packages/react-server/src/lib/router.tsx
- packages/react-server/src/plugin/ast-utils.ts
- packages/react-server/src/plugin/index.ts
Let's try to sync with cleaner structure in https://github.com/hi-ogawa/vite-environment-examples/tree/main/examples/react-server
- indeed there are unused imports https://github.com/hi-ogawa/vite-plugins/pull/298/commits/56ebc4473e3dc2ccbc7e6ffa5cad39c38e720540
Next plan is to split `plugin/index.ts` into `features`.
> refactor(react-server): minor cleanup

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/dynamic/catchall/[...any]/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/catchall/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/catchall/static/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/layout.tsx
- packages/react-server/src/lib/router.tsx
It looks a little shaky, but this is one way to do it.
> feat(react-server): support catch-all dynamic route

- packages/react-server/examples/basic/e2e/basic.test.ts
We already check the most important case to catch stale server module hydration error, but why not add more:
https://github.com/hi-ogawa/vite-plugins/blob/48f1844d62aba59f9a17cb58ec73c9c5286cd6c4/packages/react-server/examples/basic/e2e/basic.test.ts#L231-L233
> test(react-server): test SSR after HMR

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/src/features/use-client/plugin.ts
- packages/react-server/src/features/use-client/server.tsx
- packages/react-server/src/plugin/index.ts
- follow up to https://github.com/hi-ogawa/vite-plugins/pull/315
Probably we should consider entirely virtual module centered approach (not only `node_modules`), but for now, it might be possible to simply adjust our existing `noramlizeClientReferenceId` to take hmr timestamp into account.
---
However, `?t=...` injection doesn't happen for ssr import analysis (unless we use new module runner `injectInvalidationTimestamp` mode https://github.com/vitejs/vite/pull/16400), so we actually need to strip that out during ssr `importWrapper` again.
---
And good news is that this is going to fix this non-ideal HMR behavior added in:
- https://github.com/hi-ogawa/vite-plugins/pull/265
> fix(react-server): noramlize client reference with `?t=` query (hmr timestamp)

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/dynamic/[id]/page.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/examples/basic/src/routes/test/loading/[id]/page.tsx
- packages/react-server/examples/basic/src/routes/test/loading/layout.tsx
- packages/react-server/examples/basic/src/routes/test/loading/page.tsx
- packages/react-server/src/lib/__snapshots__/router.test.ts.snap
- packages/react-server/src/lib/router.tsx
I think this is what's more important so that other convention (e.g. `loading` https://github.com/hi-ogawa/vite-plugins/pull/327) should work or userland implement is easier.
> feat(react-server): remount subtree on dynamic segment change

- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/assets/plugin.ts
- packages/react-server/src/features/server-action/plugin.tsx
- packages/react-server/src/features/use-client/plugin.ts
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/plugin/utils.tsx
Moving out some code from `plugin/index.ts` to corresponding `features/plugin.ts` when possible.
> refactor(react-server): organize plugins

- packages/react-server/src/features/server-action/browser.tsx
- packages/react-server/src/features/server-action/react-server.tsx
- packages/react-server/src/features/server-action/server.tsx
- packages/react-server/src/features/use-client/react-server.tsx
Picking up diff from https://github.com/hi-ogawa/vite-plugins/pull/331
We could probably add `/* @__PURE__ */ $$proxy(...)` from transform plugin side, but `__NO_SIDE_EFFECTS__` should be also fine for now.
Source https://github.com/hi-ogawa/vite-plugins/blob/1b276422a7fe68c908e1c279528b8a3d8fbb29e3/packages/react-server/examples/starter/src/routes/layout.tsx#L1-L3
Build output in `packages/react-server/examples/starter/dist/rsc/index.js`
- before
```ts
...
const Link = registerClientReference("SGjedgC19ilj85OGI0xm9X7OjaT_pYP5IBJLJN739tk", "Link");
registerClientReference("SGjedgC19ilj85OGI0xm9X7OjaT_pYP5IBJLJN739tk", "LinkForm");
registerClientReference("SGjedgC19ilj85OGI0xm9X7OjaT_pYP5IBJLJN739tk", "routerRevalidate");
registerClientReference("SGjedgC19ilj85OGI0xm9X7OjaT_pYP5IBJLJN739tk" …
```
> fix(react-server): tree shake unused references by `__NO_SIDE_EFFECTS__`

- packages/react-server/src/features/assets/plugin.ts
- packages/react-server/src/features/router/plugin.ts
- packages/react-server/src/plugin/index.ts
Need to fix client css first
- https://github.com/hi-ogawa/vite-plugins/pull/342
> feat(react-server): preload css

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/css/_client.tsx
- packages/react-server/examples/basic/src/routes/test/css/css-client-module.module.css
- packages/react-server/examples/basic/src/routes/test/css/css-client-normal.css
- packages/react-server/examples/basic/src/routes/test/css/page.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/assets/plugin.ts
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/plugin.ts
It looks like I haven't test this case and it turns out I get FOUC (both dev and build), which needs to be fixed before thinking about preload.
For build, `<link rel="stylesheet" ... />` is injected during `preload`. We need to take control of that probably https://github.com/vitejs/vite/blob/147e9228bb1c75db153873761eb7a120a2bd09a4/packages/vite/src/node/plugins/importAnalysisBuild.ts#L119-L129
- head rendering behavior doesn't allow detaching stylesheet https://react.dev/reference/react-dom/components/link#special-rendering-behavior
probably this is fine for now and we can follow up later.
> fix(react-server): fix client css FOUC

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/src/features/assets/css.ts
- packages/react-server/src/plugin/index.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/345
We should maybe replace `transformRequret("...css?direct")` with `ssrLoadModule("...css")`, so there won't be `?direct` module. I can follow up with this approach later.
> fix(react-server/css): fix client css module hmr

- packages/react-server/src/features/server-action/plugin.tsx
- packages/react-server/src/features/use-client/plugin.ts
Cleaning up some old approach, which is already replaced in Vite 6 version https://github.com/hi-ogawa/vite-environment-examples/tree/main/examples/react-server
> refactor: simplify `virtual:client-references`

- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/server-action/browser.tsx
- packages/react-server/src/features/server-action/react-server.tsx
- packages/react-server/src/features/server-action/server.tsx
- packages/react-server/src/features/use-client/browser.tsx
- packages/react-server/src/features/use-client/react-server.tsx
- packages/react-server/src/features/use-client/server.tsx
Adopting the same naming from
- https://github.com/hi-ogawa/vite-environment-examples/pull/88
> refactor: rename react imports

- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/features/server-component/utils.tsx
This prevents unnecessary cache miss for prerendered flight response.
> refactor: encode stream request metadata in http header

- packages/react-server/examples/basic/src/routes/test/page.tsx
Now that this is too obvious, so let's remove it to avoid depending on external service
> chore: remove fetch demo

- .github/workflows/ci.yml
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/playwright.config.ts
Just in case to not introducing some features not available on cloudflare.
Preview build e2e is fast, so doubling that is okay.
> test: e2e cf build

- packages/react-server/examples/prerender/README.md
- packages/react-server/examples/prerender/misc/cf/build.mjs
- packages/react-server/examples/prerender/src/routes/layout.tsx
- packages/react-server/src/features/prerender/plugin.ts
- packages/react-server/src/features/server-component/utils.tsx
- packages/react-server/src/plugin/index.ts
Tweaking this again since Cloudflare Pages only matches `/abc` to `/abc/index.html` (cf. https://github.com/hi-ogawa/vite-plugins/pull/375).
```
/posts/index.html
/posts/__f.data
/posts.html
/posts__f.data
```
> fix: tweak prerender output

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/router/__snapshots__/tree.test.ts.snap
- packages/react-server/src/features/router/tree.test.ts
- packages/react-server/src/features/router/tree.ts
- packages/react-server/src/features/router/utils.tsx
It doesn't seem worth it to consider trailing slash in down stream logic, so let's just enforce at the top level and assume no trailing slash.
> fix: enforce no trailing slash

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/_client.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/examples/basic/src/routes/test/revalidate/[id]/page.tsx
- packages/react-server/examples/basic/src/routes/test/revalidate/layout.tsx
- packages/react-server/examples/basic/src/routes/test/revalidate/page.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/utils.test.ts
- packages/react-server/src/features/router/utils.tsx
- packages/react-server/src/features/server-action/react-server.tsx
- packages/react-server/src/features/server-component/utils.tsx
- packages/react-server/src/lib/client/link.tsx
- closes https://github.com/hi-ogawa/vite-plugins/issues/390
I thought I should refactor route data handling first, but it's probably fine to go with this one now.
> feat: refine route data revalidation

- packages/vite-node-miniflare/examples/react-router/vite.config.ts
- packages/vite-node-miniflare/examples/react/vite.config.ts
- packages/vite-node-miniflare/examples/remix/app/entry.server.tsx
- packages/vite-node-miniflare/examples/remix/vite.config.ts
Cherry-picking change from https://github.com/hi-ogawa/vite-plugins/pull/396
Currently `react-dom/server.browser` is resolved and it looks like it's going to break by the latest experimental react.
> fix: fix react-dom/server conditions in workerd

- packages/react-server/src/entry/server.tsx
Somehow this was causing `&nbsp;` to be rendered as `Â` when `<meta charSet="UTF-8" />` is not included like in https://github.com/hi-ogawa/vite-plugins/pull/409.
Probably forcing charset in the response should be fine.
> fix: set html response as charset=utf-8

- packages/react-server/examples/next/tsconfig.json
- packages/react-server/src/next/plugin.ts
Next.js's default `jsx: preserve` breaks, but we can workaround this on esbuild config side.
Not really a big deal, but this will reduce one patch needed for codemod.
> fix(next): force esbuild jsx transform

- packages/react-server/examples/next/app/navigation/README.md
- packages/react-server/examples/next/app/navigation/not-found/error.tsx
- packages/react-server/examples/next/app/navigation/not-found/servercomponent/page.tsx
- packages/react-server/examples/next/app/navigation/not-found/style.module.css
- packages/react-server/examples/next/app/navigation/redirect/result/page.tsx
- packages/react-server/examples/next/app/navigation/redirect/servercomponent-2/page.tsx
- packages/react-server/examples/next/app/navigation/redirect/servercomponent/page.tsx
- packages/react-server/examples/next/app/navigation/router/dynamic-gsp/[slug]/page.tsx
- packages/react-server/examples/next/app/navigation/router/page.tsx
- packages/react-server/examples/next/e2e/basic.test.ts
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/features/use-client/plugin.ts
- packages/react-server/src/next/compat/navigation.react-server.tsx
- packages/react-server/src/next/compat/navigation.tsx
- packages/react-server/src/next/plugin.ts
- packages/react-server/src/plugin/index.ts
As seen in https://github.com/hi-ogawa/vite-plugins/pull/420, `"scan"` phase sees `navigation.react-server.js`, so it breaks build.
This is a workaround to give up scanning of `"use server"` imported from client, but this is somewhat edge case, so let's go with this for now for next compat.
> fix: workaround scan build error with conditioned exports

- packages/react-server/src/features/assets/plugin.ts
When server entry is `react-server-next/vite/entry-server`, initial crawling fails to grab css from user's server routes.
We should revisit the strategy here in general, but for now, ensuring `@hiogawa/react-server/entry-react-server` helps the issue on next tailwind https://github.com/hi-ogawa/reproductions/tree/main/vite-next.
---
Well, it looks like some resolution is broken and it ended up with `@hiogawa/react-server/entry-react-server.js`.
Let's try `virtual:server-routes` instead?
---
Actually, I'm not sure why `examples/next` is working without this. Anyway, let's dig in later...
> fix: fix initial server css crawling

- packages/react-server/src/plugin/index.ts
`closeBundle` is called regardless of build error, so moving it `writeBundle` (like Sveltekit and Remix do) helps stopping a build properly when first build is broken.
Currently, ssr build continues (and is destined to fail) even if browser build fails and the error message in that case is very cryptic like:
```
▶▶▶ REACT SERVER BUILD (browser) [3/4]
✓ 38 modules transformed.
▶▶▶ REACT SERVER BUILD (ssr) [4/4]
vite v5.2.3 building SSR bundle for production...
✓ 2 modules transformed.
x Build failed in 9ms
x Build failed in 881ms
error during build:
Error: [vitePluginReactServer:build] [virtual-virtual:route-manifest] Could not load virtual:route-manifest (imported by ../../dist/entry/server.js): TinyAssertionError
```
> fix: avoid ssr build on browser build failure

- packages/react-server-next/src/vite/index.ts
- packages/react-server/examples/next/app/actions/client/layout.tsx
- packages/react-server/examples/next/app/test/page.tsx
- packages/react-server/package.json
- packages/react-server/src/features/use-client/plugin.ts
- packages/react-server/src/plugin/index.ts
- pnpm-lock.yaml
- close https://github.com/hi-ogawa/vite-plugins/issues/428
The previous issue was that when some package changes exports based on condition e.g.
```ts
// some-lib package.json
{
exports: {
".": {
"react-server": "./some-lib.react-server.js",
"default": "./some-lib.js",
}
}
}
// some-lib.js
export const clientLib = ...;
// some-lib.react-server.js
export const serverLib = ...
```
then scanning of a following user code fails since scanning happens with `"react-server"` condition:
```ts
// some-user-code.js
"use client"
import { clientLib } from "some-lib";
// => Rollup error for missing export
export const thing = ...
```
This PR fixes this issue by import as side effects and all exports to `undefined`, which still allows scanning module graph and discover server/client references as …
> fix: robust server reference build scan

- packages/react-server-next/package.json
- packages/react-server/examples/next/package.json
- packages/react-server/examples/next/vite.config.ts
- pnpm-lock.yaml
Having `vite` in `dependencies` was for trying to have some zero config magic, but striving for that can be later. Let's just go with simpler one for now.
This would also help providing types from `"types": ["vite/client"]`.
> refactor(next): move vite to peer deps

- packages/react-server/examples/next/app/actions/client/actions.ts
- packages/react-server/examples/next/app/actions/client/page.tsx
- packages/react-server/examples/next/vite.config.ts
- packages/react-server/src/plugin/index.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/427
Not an essential feature (i.e. easily implemented on userland), but next.js code base includes this in a random place, so let's not break on that.
> feat: validate server-only and client-only

- packages/react-server-next/index.d.ts
- packages/react-server-next/package.json
- packages/react-server/examples/next/next-env.d.ts
- packages/react-server/examples/next/tsconfig.json
By providing an ambient type from the root `index.d.ts`, that will be picked up automatically via `next-env.d.ts`.
> feat(next): ambient type via `next-env.d.ts`

- packages/react-server/src/plugin/index.ts
I just noticed this flag when checking autocomplete. It looks like Waku already make use of it as well https://github.com/dai-shi/waku/blob/aa8b021a2f1ab073abc601129b5d0d6c3bda8ca1/packages/waku/src/lib/builder/build.ts#L126-L127
I don't think this would affect perf much, but build logs get cleaner with this.
> perf: set `build.write: false` during scan

- packages/react-server-next/package.json
- packages/react-server-next/src/compat/headers.tsx
- pnpm-lock.yaml
This would unblock this demo https://app-router-vite.vercel.app/streaming/node/product/1
> fix(next): shim `cookies` using `@edge-runtime/cookies`

- packages/react-server-next/src/compat/index.tsx
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/e2e/helper.ts
- packages/react-server/examples/basic/src/routes/layout.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/examples/basic/src/routes/test/metadata/page.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/meta/server.tsx
- packages/react-server/src/features/meta/utils.ts
- packages/react-server/src/features/router/__snapshots__/server.test.tsx.snap
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/server.tsx
- packages/react-server/src/features/router/utils.tsx
- packages/react-server/src/server.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/397
For now, let's support minimal features to make simple next example looks a bit prettier.
> feat: support `metadata` export

- packages/react-server-next/src/compat/navigation.tsx
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/dynamic/_cilent.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/_utils.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/[p2]/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/[p2]/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/static/[q1]/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/static/[q1]/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/static/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/static/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/_client.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/page.tsx
- packages/react-server/examples/next/.gitignore
- packages/react-server/src/client.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/router/__snapshots__/server.test.tsx.snap
- packages/react-server/src/features/router/__snapshots__/tree.test.ts.snap
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/server.tsx
- packages/react-server/src/features/router/tree.ts
- packages/react-server/src/features/router/utils.tsx
- packages/react-server/src/lib/client/router.tsx
- packages/react-server/src/runtime-client.ts
This is an essential as a core feature and also unblocks next compat https://github.com/hi-ogawa/next-app-router-playground/pull/1
- `useSelectedLayoutSegments`
- `useSelectedLayoutSegment`
> feat: add hooks to provide current route params

- packages/react-server/examples/basic/playwright.config.ts
- packages/react-server/examples/basic/vite.config.ts
Currently `pnpm test-e2e --headed -g error` fails when running locally without manually adding `CI=1`.
Adding a explicit condition `E2E=true` instead.
> test: tweak env

- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/utils/stream-script.tsx
Investigating cf e2e error in https://github.com/hi-ogawa/vite-plugins/pull/456.
It looks like it's not guaranteed that `</body>` would shows up nicely in a single chunk...
```
[injectStreamScript] { i: 2, chunk: 'body></html>' }
[injectStreamScript] { i: 3, chunk: '' }
```
---
Let's revive `StreamTransfer` removed in https://github.com/hi-ogawa/experiments/pull/26.
EDIT: Well, this has a problem for two-pass ssr...
---
Not sure but Next.js might be relying on buffering to somehow ensure tag to be not split?
https://github.com/vercel/next.js/blob/b2eafbf6b3550b1f0d643c326515814610747532/packages/next/src/server/stream-utils/node-web-streams-helper.ts#L382-L387
> fix: fix ssr flight stream injection by buffering

- .github/workflows/ci.yml
- packages/react-server-next/package.json
- packages/react-server-next/src/vite/adapters/cloudflare/build.ts
- packages/react-server-next/src/vite/adapters/cloudflare/entry.ts
- packages/react-server-next/src/vite/adapters/index.ts
- packages/react-server-next/src/vite/adapters/node/entry.ts
- packages/react-server-next/src/vite/adapters/vercel/build.ts
- packages/react-server-next/src/vite/adapters/vercel/entry.ts
- packages/react-server-next/src/vite/index.ts
- packages/react-server-next/tsup.config.ts
- packages/react-server/examples/next/README.md
- packages/react-server/examples/next/package.json
- pnpm-lock.yaml
For https://github.com/hi-ogawa/next-app-router-playground/pull/2
Just copying some scripts from `packages/react-server/examples/basic/misc/cf/build.js` and `packages/react-server/examples/basic/misc/vercel/build.js`.
> feat(next): adapters for deployment

- packages/react-server/examples/basic/src/routes/layout.tsx
- packages/react-server/examples/next/app/layout.tsx
- packages/react-server/examples/next/e2e/basic.test.ts
- packages/react-server/examples/prerender/src/routes/layout.tsx
- packages/react-server/examples/starter/src/routes/layout.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/next/ssr.tsx
For now, quick workaround for https://github.com/hi-ogawa/next-app-router-playground/pull/1
The reason why `viewport` is separated from `metadata` is explained well below, so probably we should catch up later, but it's fine for now.
- https://github.com/vercel/next.js/pull/57302
> feat: add default meta viewport

- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/router/manifest.ts
- packages/react-server/src/features/router/plugin.ts
Currently the entire `RouteManifest` is inlined in the ssr html as `<script>self.__routeManifest = ...</script>`, but this is probably not good.
Like Remix does, let's separate assets for manifest so it can be fetched separately.
> perf: emit route manifest as a separate asset

- packages/react-server-next/src/compat/navigation.tsx
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/[p2]/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/[p2]/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/static/[q1]/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/static/[q1]/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/static/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/[p1]/static/page.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/_client.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/layout.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/selected/page.tsx
- packages/react-server/src/client.tsx
- packages/react-server/src/features/router/client.tsx
Just noticed sidebar nav active link is not working https://github.com/hi-ogawa/next-app-router-playground/pull/1. It looks like "selected" should include not only dynamic parameter but everything along the path.
> fix(next): fix `useSelectedLayoutSegment`

- packages/react-server-next/src/compat/navigation.tsx
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/dynamic/_cilent.tsx
- packages/react-server/examples/basic/src/routes/test/dynamic/_utils.tsx
- packages/react-server/src/client.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/utils.tsx
- packages/react-server/src/lib/client/router.tsx
I started with `useRouter` which exposes browser location, which is probably necessary to implement demo like https://rsc-experiment-hiroshi.vercel.app/test/transition, but it looks like Next.js doesn't do it and only provides flight tree location via `usePathname` etc... of `next/navigation`.
For now, we keep current `useRouter`, but let's expose `useLocation` for quick next compatibility.
> feat: add `useLocation` to provide server url

- packages/react-server/examples/basic/src/routes/test/other/page.tsx
- packages/react-server/src/features/router/__snapshots__/server.test.tsx.snap
- packages/react-server/src/features/router/server.tsx
At the moment, the lack of this `searchParams` is causing 500 on https://app-router-vite.vercel.app/patterns/search-params
> feat: add `PageProps.searchParams`

- .github/workflows/ci.yml
- packages/react-server-next/src/vite/adapters/vercel/build.ts
- packages/react-server/examples/prerender/misc/vercel/build.js
- packages/react-server/examples/prerender/misc/vercel/entry-node.js
- packages/react-server/src/server.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/474
After setting up `overrides`, it looks okay now https://demo-rsc-prerender.vercel.app/posts/1
<details><summary>show screenshot</summary>
</details>
> fix(next): correctly setup ssg html on vercel adapter

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/api/dynamic/[id]/route.ts
- packages/react-server/examples/basic/src/routes/test/api/page.tsx
- packages/react-server/examples/basic/src/routes/test/api/static/route.ts
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/features/router/api-route.ts
- packages/react-server/src/features/router/server.tsx
- packages/react-server/src/features/router/tree.ts
- packages/react-server/src/plugin/index.ts
> feat: api routes

- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/request-context/server.ts
- packages/react-server/src/server.ts
- follow up https://github.com/hi-ogawa/vite-plugins/pull/484
Overall structure is fine but Next.js style API `headers, cookies, revalidatePath` feels clumsy (and especially `RequestCookies` and `RequestCookies` trick required for that seems convoluted), so let's move that to just next compat.
> refactor: tweak request context API

- packages/react-server-next/package.json
- packages/react-server-next/src/compat/image.tsx
- packages/react-server/examples/next/e2e/basic.test.ts
- packages/react-server/examples/next/e2e/helper.ts
- pnpm-lock.yaml
It looks like React already automatically add `<link rel="preload" as="image" ...>` for `<img>`.
Probably explicitly doing `ReactDOM.preload` is only for higher priority?
> feat(next): support `Image.priority`

- packages/react-server/src/plugin/index.ts
It looks like this happens on local dev in monorepo links. For now, let's just make it easier by including the deps.
```
<-- GET / 200 229ms
5:50:30 PM [vite] ✨ new dependencies optimized: @edge-runtime/cookies
5:50:30 PM [vite] ✨ optimized dependencies changed. reloading
```
> fix: fix late deps optimization on local dev

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/action/_action2.tsx
- packages/react-server/examples/basic/src/routes/test/action/_client.tsx
- packages/react-server/examples/basic/src/routes/test/action/_client2.tsx
- packages/react-server/examples/basic/src/routes/test/action/page.tsx
Just in case. This pattern also tests deeper reference discovery of
```
server (page) -> client (_client) -> server (_action2) -> client (_client2)
```
---
Also just remembered "temporary references" thing, but haven't tested nor integrated yet. Will do it later.
- https://github.com/facebook/react/pull/28564
> test: test action returning components

- packages/react-server-next/src/compat/navigation.tsx
- packages/react-server/examples/basic/src/routes/test/revalidate/page.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/server.tsx
- packages/react-server/src/features/server-component/utils.tsx
I forgot to include this breaking change in v0.3.0.
> refactor!: string only for `RevalidationType`

- packages/react-server/src/features/router/__snapshots__/tree.test.ts.snap
- packages/react-server/src/features/router/tree.test.ts
- packages/react-server/src/features/router/tree.ts
Found out this is broken when testing it on https://app-router-vite.vercel.app/error-handling/electronics
---
OK, I remember why not-found handling is tricky, so stripping off `processNotFound` wasn't probably correct https://github.com/hi-ogawa/vite-plugins/pull/517/commits/41c9204d39e91de9e8c01eac8e02a67657341649
At this point, I'm not even sure what's most "natural", so we can probably just postpone tie-break between multiple "not-found" for the sake of fixing "page > not-found" tie-break, which is a way more crucial.
> fix: match dynamic page over not-found

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/catchall-opt/[[...slug]]/page.tsx
- packages/react-server/examples/basic/src/routes/test/catchall-opt/layout.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/src/features/router/__snapshots__/tree.test.ts.snap
- packages/react-server/src/features/router/tree.test.ts
- packages/react-server/src/features/router/tree.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/515
Well, it turned out our catch-all `[...any]` works already as optional... So we need to find a way to make the current one strict.
> feat: optional catch-all route

- packages/react-server-next/src/compat/navigation.tsx
Just noticed `tsc` is failing in app-router demo
```
ui/tab.tsx:17:44 - error TS2554: Expected 0 arguments, but got 1.
17   const segment = useSelectedLayoutSegment(parallelRoutesKey);
~~~~~~~~~~~~~~~~~
```
> fix(next): fix `useSelectedLayoutSegment` type compat

- packages/react-server/src/features/assets/plugin.ts
- packages/react-server/src/features/client-component/plugin.ts
- packages/react-server/src/features/server-action/plugin.tsx
- packages/react-server/src/features/server-action/server.tsx
- packages/react-server/src/global.ts
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/plugin/utils.tsx
- packages/react-server/src/utils/misc.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/527
Mostly trying to back port this one from webpack-rsc, but it's actually trickier since we need a different machinery during dev.
- https://github.com/hi-ogawa/experiments/pull/41
Also, just remembered we want to port this one in Vite 6 example too
- https://github.com/hi-ogawa/vite-environment-examples/pull/84
- https://github.com/hi-ogawa/vite-environment-examples/pull/84
> fix: normalize reference id

- .gitignore
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/action/_client.tsx
- packages/react-server/examples/basic/src/routes/test/action/page.tsx
- packages/react-server/src/entry/browser.tsx
- alternative of https://github.com/hi-ogawa/vite-plugins/pull/529
- closes https://github.com/hi-ogawa/vite-plugins/issues/387
- how to handle nojs action SSR? Currently error is completely silenced and it simply re-render SSR.
- we cannot do this if we want nojs action SSR.
> fix: rethrow action error on client

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/error/boundary/dir/[id]/page.tsx
- packages/react-server/examples/basic/src/routes/test/error/boundary/dir/error.tsx
- packages/react-server/examples/basic/src/routes/test/error/boundary/dir/page.tsx
- packages/react-server/examples/basic/src/routes/test/error/boundary/layout.tsx
- packages/react-server/examples/basic/src/routes/test/error/boundary/not-found.tsx
- packages/react-server/examples/basic/src/routes/test/error/boundary/page.tsx
- packages/react-server/examples/basic/src/routes/test/error/layout.tsx
- packages/react-server/src/features/error/error-boundary.tsx
- packages/react-server/src/features/error/shared.ts
Now that we have a special semantics for redirect error and not found error, our general `ErrorBoundary` shouldn't catch those.
> fix: don't catch known errors from general ErrorBoundary

- packages/react-server-next/src/compat/navigation.tsx
Forgot to push the last commit to 
- https://github.com/hi-ogawa/vite-plugins/pull/536
> chore(next): re-export `useServerInsertedHTML`

- packages/react-server-next/src/vite/index.ts
- packages/react-server/src/plugin/index.ts
Minor cleanup to properly structure `ReactServerPluginOptions` and `ReactServerNextPluginOptions` so that it allows `routeDir: "src/app"` for example.
Technically breaking since I need to manually add `prerender: (_manifest, presets) => presets.generateStaticParams()` in https://github.com/hi-ogawa/next-app-router-playground/pull/1
> feat(next)!: expose `ReactServerPluginOptions`

- packages/react-server-next/CHANGELOG.md
- packages/react-server/CHANGELOG.md
It looks nice to be able to easily see timeline. 
For old ones, we can use `git blame` to collect the date:
```sh
$ git blame packages/react-server/CHANGELOG.md | grep '## v'
b084d8e4f (Hiroshi Ogawa 2024-07-11 08:38:50 +0900   3) ## v0.3.2 (2024-07-11)
561407ed9 (Hiroshi Ogawa 2024-07-09 11:07:33 +0900  13) ## v0.3.1
68669d170 (Hiroshi Ogawa 2024-07-04 12:13:13 +0900  24) ## v0.3.0
3a7b13138 (Hiroshi Ogawa 2024-07-01 17:55:24 +0900  35) ## v0.2.10
930047f4a (Hiroshi Ogawa 2024-06-30 11:59:25 +0900  42) ## v0.2.9
b872e00ba (Hiroshi Ogawa 2024-06-27 16:33:42 +0900  53) ## v0.2.8
...
```
But actually, `CHANGELOG.md` didn't exist initially, so we should probably need git log of package.json `"version"`:
```sh
git log -L 2,3:packages/react-server/package.json
```
> chore: add changelog date

- packages/react-server/package.json
- pnpm-lock.yaml
Forgot to remove these deps when they are moved to `react-server-next` compat package
- https://github.com/hi-ogawa/vite-plugins/pull/413
- https://github.com/hi-ogawa/vite-plugins/pull/418
> chore: remove unused deps

- packages/react-server/package.json
- packages/react-server/src/features/router/client/store-utils.tsx
- packages/react-server/src/plugin/index.ts
- pnpm-lock.yaml
- closes https://github.com/hi-ogawa/vite-plugins/issues/542
Just created a mini version and hopefully this works fine.
> refactor: use own `useSyncExternalStoreWithSelector`

- packages/react-server/src/features/assets/css.ts
- packages/react-server/src/features/assets/plugin.ts
Probably this is the cause of the warning in https://github.com/hi-ogawa/lucia-auth-examples/pull/1. Without ssr, server transform request is resolving a browser entry.
```
5:42:28 PM [react-server] Pre-transform error: Failed to resolve import "@node-rs/argon2-wasm32-wasi" from "node_modules/.pnpm/@node-rs+argon2@1.8.3/node_modules/@node-rs/argon2/browser.js?v=1e8f26d9". Does the file exist?
```
Eventually we'll need to rework all this, but for now this can go first. Related PRs:
- https://github.com/hi-ogawa/vite-plugins/pull/496
- https://github.com/hi-ogawa/vite-plugins/pull/494
> fix: use ssr `transformRequest` for css crawling on server

- packages/react-server-next/src/vite/adapters/index.ts
- packages/react-server-next/src/vite/adapters/vercel-edge/entry.ts
- packages/react-server-next/src/vite/adapters/vercel/build.ts
- packages/react-server-next/src/vite/adapters/vercel/entry.ts
- packages/react-server-next/tsup.config.ts
- packages/react-server/examples/next/package.json
- closes https://github.com/hi-ogawa/vite-plugins/issues/550
> feat(next): vercel node runtime adapter

- packages/react-server-next/src/compat/server.tsx
- packages/react-server/examples/next/e2e/basic.test.ts
- packages/react-server/examples/next/middleware.ts
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/entry/ssr.tsx
- packages/react-server/src/features/next/cookie.ts
- packages/react-server/src/features/next/middleware.ts
- packages/react-server/src/features/next/request.ts
- packages/react-server/src/features/request-context/server.ts
- packages/react-server/src/features/router/api-route.ts
- packages/react-server/src/features/server-action/redirect.ts
- packages/react-server/src/features/server-action/server.tsx
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/plugin/virtual.d.ts
- packages/react-server/src/server.ts
- `clone`
- it was just next-auth config issue... https://github.com/hi-ogawa/next-learn/pull/1/commits/376b361c98d9aff79bfc40d116e60d12bdcb2f74
> feat: support middleware

- packages/react-server/examples/next/app/test/page.tsx
- packages/react-server/examples/next/e2e/basic.test.ts
- packages/react-server/examples/next/middleware.ts
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/error/error-boundary.tsx
- packages/react-server/src/features/error/shared.ts
- packages/react-server/src/features/server-action/redirect.ts
We need to generalize action redirection to any flight request redirection for `next-auth` https://github.com/hi-ogawa/next-learn/pull/1
> fix: handle middleware redirection of flight request

- packages/react-server/examples/basic/deps/mixed/README.md
- packages/react-server/examples/basic/deps/mixed/client.js
- packages/react-server/examples/basic/deps/mixed/index.d.ts
- packages/react-server/examples/basic/deps/mixed/index.js
- packages/react-server/examples/basic/deps/mixed/package.json
- packages/react-server/examples/basic/deps/server-component/package.json
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/routes/test/deps/layout.tsx
- packages/react-server/examples/basic/src/routes/test/deps/page.tsx
- packages/react-server/examples/basic/src/routes/test/deps/react-tweet/page.tsx
- packages/react-server/examples/basic/vite.config.ts
- packages/react-server/src/features/client-component/plugin.ts
- pnpm-lock.yaml
- related https://github.com/hi-ogawa/vite-plugins/issues/379
- https://github.com/hi-ogawa/vite-plugins/pull/385
- strip-off `?v=` (this still causes dual modules when client is imported from both server (no `?v=`) and client (with `?v=`)
- pre-bundling?
- vendoring...?
- package manager level workaround?
- probably flaky to test react-tweet, so let's add fixture package to simulate the same.
> fix: partial support of server-client-mixed package + chore: add react-tweet demo

- packages/react-server/package.json
- pnpm-lock.yaml
- https://github.com/hi-ogawa/vite-plugins/pull/558
- https://github.com/hi-ogawa/vite-plugins/pull/545
While analyzing various output of `@vercel/og` example https://github.com/hi-ogawa/vite-plugins/pull/558, I noticed internal dependencies (namely `@edge-runtime/cookies` and `@tanstack/history`) shows up as bare import of output e.g. `dist/server.js` since `@hiogawa/react-server` are bundled.
Such import shouldn't be possible to resolve, so I'm not sure even why esbuild (used for adapter build) is able to bundle those deps. 
Either we need to bundle runtime deps at the package level (i.e. tsup + `devDependencies`) or add those manually to `noExternal` for vite build. I'm thinking the former is better for simplicity since these two are implementation detail.
> fix: bundle runtime deps

- packages/react-server/examples/og/package.json
- packages/react-server/examples/og/test-bundle.js
- pnpm-lock.yaml
rolldown was crashing, but It looks like `platform: "node"` is needed. Also added a few rollup plugins to bundle similar to esbuild.
> chore: fix og test bundle script

- packages/react-server/examples/og/test-bundle.js
I thought rolldown is slow, but it turned out node was just hanging. It looks like force-exit is necessary for now:
- https://github.com/rolldown/rolldown/pull/1097
> chore: fix rolldown exit

- packages/react-server/examples/basic/deps/use-client/index.d.ts
- packages/react-server/examples/basic/deps/use-client/package.json
- packages/react-server/examples/basic/deps/use-client/re-export/all.js
- packages/react-server/examples/basic/deps/use-client/re-export/explicit.js
- packages/react-server/examples/basic/deps/use-client/re-export/index.d.ts
- packages/react-server/examples/basic/deps/use-client/re-export/index.js
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/deps/page.tsx
- packages/react-server/src/features/client-component/plugin.ts
- packages/react-server/src/features/server-action/plugin.tsx
It looks like we'll need this for material ui
- https://github.com/hi-ogawa/material-ui/pull/1
Probably Next.js happens to support this since mui is a broken esm package. Not sure what to do, so just loosen the check, add a test and call it a day.
- I think they don't support it either https://github.com/vercel/next.js/blob/4515db1e8376f1df84752377d9f50bf42ba0ddcb/packages/next/src/build/webpack/loaders/next-flight-loader/index.ts#L93-L101
- probably the reason why mui works is that Next.js probably picks up cjs entries, in which case they have a generous support.
- well, `@mui/material` is not a genuine ESM at all https://publint.dev/@mui/material@5.16.4 and it doesn't run on plain NodeJS (i.e. broken package)
> fix: `ignoreExportAllDeclaration` during client/server transform

- packages/ssr-css/src/collect.ts
- packages/ssr-css/src/plugin.ts
Thanks for this useful plugin! I was confused about getting a 404, which actually turned out to be a false warning because everything happens in this virtual module.
Sending an empty response gets rid of this.
> fix(vite-plugin-ssr-css): handle css virtual module via `ssrLoadModule`

- packages/pre-bundle-new-url/src/index.ts
Probably the plugin shouldn't intervene during dep scan because that it would steal `onLoad` hooks from Vite's `vite:dep-scan`.
> fix(pre-bundle-new-url): do nothing during dep-scan

- packages/pre-bundle-new-url/examples/basic/vite.config.ts
- packages/pre-bundle-new-url/package.json
- packages/pre-bundle-new-url/src/index.ts
Testing it on https://github.com/gkjohnson/three-gpu-pathtracer, it's eating up memory due to never-ending recursive worker bundle
- https://github.com/gkjohnson/three-mesh-bvh/blob/9718501eee2619f1015fa332d7bddafaf6cf562a/src/workers/parallelMeshBVH.worker.js#L12
> fix(pre-bundle-new-url): handle recursive worker reference

- packages/pre-bundle-new-url/README.md
- packages/pre-bundle-new-url/examples/basic/deps/worker/worker-esm.js
- packages/pre-bundle-new-url/examples/basic/deps/worker/worker.js
- packages/pre-bundle-new-url/examples/basic/src/main.js
- packages/pre-bundle-new-url/package.json
- packages/pre-bundle-new-url/src/index.ts
- pnpm-lock.yaml
It looks like it's possible to make it agnostic to Vite since `build.initialOptions` gives enough information about where to put the output. The only assumption is that output files are flattened in a single directory like Vite's deps optimization.
> feat(pre-bundle-new-url): make esbuild plugin usable outside of Vite optimizer

- packages/react-server/examples/custom-out-dir/e2e/basic.test.ts
- packages/react-server/src/entry/ssr.tsx
- packages/react-server/src/plugin/index.ts
https://github.com/hi-ogawa/vite-plugins/pull/616 restacked on main to merge it before https://github.com/hi-ogawa/vite-plugins/pull/614.
_copied description_
Currently `dist/rsc/index.js` is bundled again by ssr build and mostly just copied over to `dist/ssr/assets`. Probably we can just externalize it and let adapter handles further bundling when needed.
As seen in https://github.com/hi-ogawa/vite-plugins/pull/614, if we don't do this, we need to essentially apply the same plugin to just externalize `import "xxx.wasm"` properly, which looks redundant and error prone.
---
Also obviously this improves ssr build time:
```sh
$ pnpm -C packages/react-server/examples/basic build
...
✓ built in 349ms  // <-- ssr build
✓ built in 2.05s  // <-- total
$ pnpm -C …
```
> refactor: perf: externalize rsc build from ssr build

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/misc/cf/build.js
- packages/react-server/examples/basic/misc/vercel/build.js
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/examples/basic/src/routes/test/wasm/page.tsx
- packages/react-server/examples/basic/tsconfig.json
- packages/react-server/examples/basic/vite-plugin-wasm-module.ts
- packages/react-server/examples/basic/vite.config.ts
- pnpm-lock.yaml
- closes https://github.com/users/hi-ogawa/projects/4/views/1?pane=issue&itemId=74354460
- related https://github.com/hi-ogawa/vite-plugins/pull/548
<details><summary>old discussion</summary>
- https://developers.cloudflare.com/pages/functions/module-support/#webassembly-modules
---
Unfortunately, we cannot make `new URL(...)` convention as a base logic. Since cloudflare can take only `import "xxx.wasm"`, we need to make wasm module import as a common denominator and we need to lower down for other platform cf astro cloudflare adapter https://github.com/withastro/adapters/blob/cd4c0842aadc58defc67f4ccf6d6ef6f0401a9ac/packages/cloudflare/src/utils/cloudflare-module-loader.ts#L213-L216
Or we could provide a polyfill/transform for potential universal patterns like `fetch(new URL(..., …
> chore: add server wasm example

- packages/react-server-next/src/compat/og.tsx
- packages/react-server/examples/next/app/layout.tsx
- packages/react-server/examples/next/app/test/og/route.tsx
- packages/react-server/examples/next/e2e/basic.test.ts
- packages/react-server/src/features/meta/server.tsx
- packages/react-server/src/features/meta/utils.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/625
---
Even if we set `cache-control` https://github.com/hi-ogawa/vite-plugins/pull/626/commits/416aa7cb3bd809c7a75bdcb14ac680d26373c575, it doesn't look like Vercel is caching image on CDN.
For example, https://test-next-vite.vercel.app/test/og only returns `x-vercel-cache: MISS`. While on Next.js, they seem to be able to get to `x-vercel-cache: HIT` for https://app-router.vercel.app/api/og
Maybe this is something to do with `x-matched-path`? Not sure what's happening, so let's revert it for now.
> feat: support `Metadata.twitter`

- packages/react-server-next/src/vite/index.ts
It's not necessary to merge by ourselves since arrays will be concatenated automatically.
> refactor(next): simplify `envPrefix` merge

- packages/react-server-next/package.json
- partially revert https://github.com/hi-ogawa/vite-plugins/pull/559/
This one is added to help https://github.com/hi-ogawa/next-learn/pull/1 (weird import by nextauth?) but it's fairly ugly (probably it confused IDE import completion too?) so let's forget about it and remove them.
Probably users can workaround it by doing `alias` manually.
I wonder what Next.js would end up eventually
- https://github.com/vercel/next.js/pull/68455
---
Well, it looks like next-auth has fixed it already
- https://github.com/nextauthjs/next-auth/pull/11551
> refactor!: remove `next/*.js` exports

- packages/react-server/misc/test.sh
- related https://github.com/hi-ogawa/vite-plugins/pull/655
Since next version is broken, let's save `test-package` for now.
> test: pin react 19.0.0-rc-2d16326d-20240930

- package.json
- pnpm-lock.yaml
Looks like React element snapshot is not pretty-printed anymore. This might be because `@vitest/pretty-format` bundles `react-is` from React 18.
> chore(deps): update vitest

- package.json
- pnpm-lock.yaml
I though this is already the case via `link-workspace-packages=true`, but it looks like `latest` doesn't match when old commit is checked out (for example, latest is `0.4.0` but old commit is `0.3.8`). https://pnpm.io/workspaces
Let's force this via `pnpm.overrides`.
> chore: add pnpm overrides for `@hiogawa/react-server`

- packages/react-server/src/plugin/index.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/669
For now, let's use `ssrLoadModule` style server module invalidation, otherwise entire module cache resets on any changes. Also Vite has an issue with an virtual module entry full reload.
> fix: disable hmr for react server runner

- packages/react-server/src/features/request-context/utils.ts
- packages/react-server/src/plugin/index.ts
Cherry-picked from 
- https://github.com/hi-ogawa/vite-plugins/pull/673
> fix: fix async local storage global import side effect

- packages/rsc/src/core/server.ts
- packages/rsc/src/plugin.ts
I realized we can simplify this with the same idea from https://github.com/hi-ogawa/vite-plugins/pull/706
> refactor(rsc): simplify `SERVER_REFERENCE_PREFIX` trick

- biome.json
- package.json
- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/package.json
- packages/rsc/examples/basic/src/counter.tsx
- packages/rsc/examples/basic/src/server.tsx
- packages/rsc/examples/basic/src/styles.css
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/examples/react-router/e2e/basic.test.ts
- packages/rsc/examples/react-router/package.json
- packages/rsc/examples/react-router/src/entry.browser.tsx
- packages/rsc/examples/react-router/src/paper.css
- packages/rsc/examples/react-router/src/routes/about.tsx
- packages/rsc/examples/react-router/src/routes/client.tsx
- packages/rsc/examples/react-router/src/routes/home.actions.ts
- packages/rsc/examples/react-router/src/routes/home.client.tsx
- packages/rsc/examples/react-router/src/routes/home.tsx
- packages/rsc/examples/react-router/src/routes/root.client.tsx
- packages/rsc/examples/react-router/src/routes/root.tsx
- packages/rsc/examples/react-router/src/styles.css
- packages/rsc/examples/react-router/vite.config.ts
- packages/rsc/package.json
- packages/rsc/src/plugin.ts
- pnpm-lock.yaml
- Closes https://github.com/hi-ogawa/vite-plugins/issues/674
Copying https://github.com/jacob-ebey/experimental-parcel-react-router-starter/commit/f62e8e16d5a86c5281d06fe21cf696acbc491f78.
Confirmed stackblitz works too with latest tailwind v4.
---
Oops, this one breaks server HMR likely because tailwind joining to server module graph. The classic issue which we need workaround like this:
https://github.com/hi-ogawa/vite-plugins/blob/3fbb1622b028452f366243dcb92021297ceccd9b/packages/react-server/src/plugin/index.ts#L270-L289
> fix(rsc): support tailwind hmr

- packages/rsc/package.json
- packages/rsc/src/core/rsc.ts
- packages/rsc/src/core/shared.ts
- packages/rsc/src/core/ssr.ts
Follow up to https://github.com/hi-ogawa/vite-plugins/pull/754/. We can make it more robust and allow any ordering rsc and ssr `setRequireModule`.
> fix(rsc): fix `setRequireModule` call orders

- packages/rsc/package.json
- packages/rsc/src/plugin.ts
- Closes https://github.com/hi-ogawa/vite-plugins/issues/582
Probably we can use `RenderedModule.renderedExports` https://rollupjs.org/plugin-development/#generatebundle to find which exports is used in rsc build, then pass it to browser/ssr build to filter.
Let's try to do for `clientPackages` first. Technically our current `client-package-proxy` should be just applied to all client references, but that can be done later.
(Also, we should do the same for server reference, but that's less critical, so further unification is postponed...)
---
Note that `react-router` is externalized on ssr build, so that doesn't affect. The main bundle difference is in `dist/client/assets/index-xxx.js`.
- after
```sh
$ pnpm -C packages/rsc/examples/react-router build
vite v6.3.2 building SSR bundle for …
```
> feat(rsc): tree shake unused reference exports

- packages/rsc/examples/basic-core/src/rsc.tsx
- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/ssr.ts
I realized doing this for dev is meaningless. Moving previous `extra/ssr.ts` to `ssr.ts` and remove dev preload and do always only for build.
> feat(rsc): ssr modulepreload only for build

- packages/rsc/examples/react-router/src/entry.ssr.tsx
- packages/rsc/package.json
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/plugin.ts
- packages/rsc/src/rsc.ts
- packages/rsc/src/ssr.ts
- packages/rsc/src/types/index.ts
- packages/rsc/src/types/virtual.d.ts
While thinking about the proper/builtin support of "prepare destination", it seems like rsc needs to be able to encode dependency chunks into flight (aka `clientReferenceMetadata`) and ssr client uses it for "prepare destination".
To avoid build order constraints, let's use server external to load build artifact from each other similar to virtual `import-ssr` and `import-rsc`.
> feat(rsc): refactor assets manifest and expose it to rsc build

- .github/workflows/ci.yml
- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/playwright.config.ts
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/src/browser.ts
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/plugin.ts
- packages/rsc/src/ssr.ts
- packages/rsc/src/utils/base.ts
This only deals with browser assets prefix, which is a bundler concern. Additionally framework feature needs to be aware of base e.g. react router's `basename` option.
_todo_
> feat(rsc): support custom base

- packages/react-server/src/plugin/index.ts
- Closes https://github.com/hi-ogawa/vite-plugins/issues/789
Oops, I just forgot adding it and thus obviously 404.
> fix(react-server): add `findSourceMapURL` middleware

- packages/rsc/src/plugin.ts
Part of https://github.com/hi-ogawa/vite-plugins/issues/780
Vite's source map object has
```
// filename: /home/hiroshi/code/personal/vite-plugins/packages/rsc/examples/basic/src/routes/root.tsx
{
sources: ["root.tsx"],
mappings: ....
}
```
however `sources` needs to match with Vite's module url `/src/routes/root.tsx` so that the server file also lines up with client files on devtools.
> fix(rsc): fix findSourceMapURL sources

- packages/react-server/src/features/client-component/plugin.ts
- packages/react-server/src/features/server-action/browser.tsx
- packages/react-server/src/features/server-action/plugin.tsx
- packages/react-server/src/features/server-action/ssr.tsx
- packages/react-server/src/runtime/browser.ts
- packages/react-server/src/runtime/ssr.ts
- packages/rsc/examples/basic/src/routes/action-from-client/action.tsx
- packages/rsc/examples/basic/src/routes/action-from-client/client.tsx
- packages/rsc/examples/basic/src/routes/root.tsx
- packages/rsc/src/plugin.ts
- packages/rsc/src/react/browser.ts
- packages/rsc/src/react/rsc.ts
- packages/rsc/src/react/ssr.ts
- packages/transforms/src/proxy-export.test.ts
- packages/transforms/src/proxy-export.ts
- Part of https://github.com/hi-ogawa/vite-plugins/issues/780
- Supersedes https://github.com/hi-ogawa/vite-plugins/pull/783
_todo_
_examples_
https://github.com/user-attachments/assets/fd7d63d6-3a43-4fa3-89a7-be40774e49fe
> feat(rsc): support `findSourceMapURL` for `createServerReference` + feat(transforms)!: source map for proxy export transform

- packages/react-server/examples/basic/src/routes/test/action/_action.tsx
- packages/react-server/examples/basic/src/routes/test/action/_client.tsx
- packages/react-server/examples/basic/src/routes/test/action/extra/_action.tsx
- packages/react-server/examples/basic/src/routes/test/action/extra/_action2.tsx
- packages/react-server/examples/basic/src/routes/test/action/extra/page.tsx
- packages/react-server/examples/basic/src/routes/test/action/page.tsx
- packages/react-server/examples/basic/src/routes/test/cache/page.tsx
- packages/react-server/examples/basic/src/routes/test/revalidate/[id]/page.tsx
- packages/react-server/examples/basic/src/routes/test/revalidate/redirect/page.tsx
- packages/react-server/examples/basic/src/routes/test/session/_action.tsx
- packages/react-server/examples/minimal/app/_action.tsx
- packages/react-server/examples/next/app/actions/server/page.tsx
- packages/react-server/examples/postcss-tailwind/app/page.tsx
- packages/react-server/src/features/server-action/plugin.tsx
- packages/rsc/examples/basic/src/routes/action-from-client/action.tsx
- packages/rsc/examples/basic/src/routes/action-from-client/client.tsx
- packages/rsc/examples/basic/src/routes/action.tsx
- packages/rsc/examples/basic/src/routes/root.tsx
- packages/rsc/src/plugin.ts
- packages/transforms/src/hoist.ts
- packages/transforms/src/proxy-export.ts
- packages/transforms/src/server-action.ts
- packages/transforms/src/wrap-export.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/788
- also part of https://github.com/hi-ogawa/vite-plugins/issues/780 to unwrap `registerServerReference` calls
Unfortunately, the code frame cannot show original tsx file since we rely on esbuild to transpile that already.
```
12:10:26 PM [vite] Internal server error: "use server" doesn't allow non async function
Plugin: rsc:use-server
File: /home/hiroshi/code/personal/vite-plugins/packages/rsc/examples/basic/src/routes/root.tsx:40:19
100|          TestTemporaryReference,
101|          {
102|            action: (node) => {
|                    ^
103|              "use server";
104|              return /* @__PURE__ */ jsxDEV("span", { children: [
```
> fix(transforms): disallow non async function for "use server"

- packages/react-server/src/features/server-action/server.tsx
Part of https://github.com/hi-ogawa/vite-plugins/issues/780
Forgot to unwrap this one.
> fix(react-server): unwrap `registerServerReference`

- .gitignore
- packages/transforms/src/server-action.ts
- packages/transforms/src/wrap-export.test.ts
- packages/transforms/src/wrap-export.ts
Part of https://github.com/hi-ogawa/vite-plugins/issues/780
A bit of trick and I can still preserve positions for `registerServerReference`, but it feels this is getting to the limit of `MagicString` approach.
~It looks like "hoist" approach is more robust, so maybe we should just use that instead (after unifying two?)~ I think it's fine for now. Let's land this.
> fix(transforms): fix source map of `registerServerReference` calls

- packages/react-server/src/features/client-component/ssr.tsx
I don't remember why exactly we needed to strip it (cf. https://github.com/hi-ogawa/vite-plugins/pull/316). This is probably fixed after switching to module runner.
> refactor(react-server): simplify ssr client reference import

- packages/rsc/src/plugin.ts
Vite's module url is the one without `base`, so we probably need to take that into account.
> fix(rsc): fix base for findSourceMapURL

- packages/rsc/src/browser.ts
While trying to confirm no waterfall with new react-router https://github.com/hi-ogawa/vite-plugins/pull/814, I just noticed this virtual is making another round trip.
> fix(rsc): statically import client references virtual

- packages/rsc/examples/react-router/package.json
- packages/rsc/examples/react-router/src/entry.ssr.tsx
- packages/rsc/src/plugin.ts
- pnpm-lock.yaml
- (supersedes) Closes https://github.com/hi-ogawa/vite-plugins/pull/765
- related https://github.com/remix-run/react-router/pull/13467
```sh
pnpm -C packages/rsc/examples/react-router build
pnpm -C packages/rsc/examples/react-router preview
```
Before
After
> chore(deps): update react-router for ssr modulepreload

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/routes/action-from-client/action.tsx
- packages/rsc/examples/basic/src/routes/action-from-client/client.tsx
- packages/rsc/examples/basic/src/routes/root.tsx
I realized we didn't have a test for actions import from client. It looks like `useActionState` can exercise exactly that (+ also `formState`), so let's add it.
> test(rsc): test `useActionState`

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/src/entry/ssr.tsx
- packages/react-server/src/features/client-component/ssr.tsx
- packages/react-server/src/features/request-context/utils.ts
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/plugin.ts
- packages/react-server/src/plugin/index.ts
We already have per-route module prefetching, so this is redundant, but let's verify whether this works.
> feat(react-server): support prepare destination

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/routes/counter.css
- packages/rsc/examples/basic/src/server.tsx
- packages/rsc/examples/basic/src/styles.css
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/plugin.ts
There's no "RSC" convention on how to split css on server side, so this depends on frameworks (e.g. Parcel's `"use server entry"`). Here, we implement a simple sweep of css files from server entry.
> feat(rsc): support css in rsc environment

- packages/rsc/examples/react-router/src/entry.rsc.tsx
- packages/rsc/examples/react-router/src/entry.ssr.tsx
- packages/rsc/examples/react-router/src/routes/root.tsx
- packages/rsc/examples/react-router/vite.config.ts
- packages/rsc/src/extra/rsc.tsx
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/plugin.ts
- packages/rsc/src/rsc.tsx
- packages/rsc/src/ssr.tsx
- packages/rsc/tsdown.config.ts
React-router example doesn't use `@hiogawa/vite-rsc/extra/ssr`. We need to expose some utility from `@hiogawa/vite-rsc/ssr`.   
Actually we should have this one from `@hiogawa/vite-rsc/rsc` since that's where users should have their root component.
> refactor(rsc): tweak asset links api

- packages/rsc/src/plugin.ts
This is obsolete after https://github.com/hi-ogawa/vite-plugins/pull/825. It should be equivalent to have css imported from `entries.rsc`.
> refactor(rsc)!: remove `entries.css`

- packages/rsc/examples/basic/src/routes/client.tsx
- packages/rsc/examples/basic/src/server.tsx
- packages/rsc/src/extra/rsc.tsx
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/extra/utils/rsc-script.ts
- packages/rsc/src/rsc.tsx
~This one will come up when officially doing "prepare destination", so let's test the idea here.~
~On top of `react-server-dom-webpack`, this can be also supported via "reference id" encoding hack. For `react-server-dom-vite`, we can probably extend `ModuleLoading` to pass chunks map (instead of actually embedding chunks in reference metadata).~
Actually we don't need nonce for prepare destination since that's normally covered by `script-src: 'self'`.
> feat(rsc): support nonce

- packages/rsc/src/plugin.ts
Single `Record<string, string>` was too messy, so it's now enhanced to `Record</* id */ string, ClientReferenceMeta>`.
Probably this will make it easier to do things like:
- apply tree-shaking to all client references (which currently is limited to `clientPackages`)
- https://github.com/hi-ogawa/vite-plugins/pull/830
> refactor(rsc): simplify client reference mapping

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/routes/client.tsx
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/src/plugin.ts
- supersedes / closes https://github.com/hi-ogawa/vite-plugins/pull/837
Simpler approach of https://github.com/hi-ogawa/vite-plugins/pull/837.
This relies on regex magic https://github.com/vitejs/vite/pull/14221, but this allows not wrapping everything with virtual module re-exports.
This also shows that the need of client reference proxy is solely for dev optimized deps.
> feat(rsc): apply tree-shaking to all client references (2nd approach)

- packages/rsc/examples/basic/README.md
- packages/rsc/examples/basic/package.json
- packages/rsc/examples/basic/src/server.tsx
- packages/rsc/examples/basic/src/styles.css
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/examples/basic/wrangler.jsonc
I didn't know cf deployment became this easy with `wrangler.jsonc`.
https://vite-rsc-basic.hiro18181.workers.dev
> chore(rsc): deploy example

- packages/rsc/CHANGELOG.md
- packages/rsc/package.json
FOUC happens on stackblitz probably because async local storage is not implemented properly on web container :sob: 
https://stackblitz.com/github/hi-ogawa/vite-plugins/tree/05-12-chore_release_v0.2.0/packages/rsc/examples/basic?file=README.md
> chore: release v0.2.0

- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/examples/hono/vite.config.ts
- packages/rsc/examples/react-router/vite.config.ts
- packages/rsc/src/plugin.ts
Probably this is more framework concern, so we don't have to bother this since they would want to manage `optimizeDeps.entries` based on their own convention.
As a general rsc solution, what we want to actually achieve is something like crawled client references to eager trigger scan during `holdUntilCrawlEnd` phase, so there's no lazy discover happens. Is it possible? (for example, triggering `transformRequest(clientReference)` early before or during first rendering? But I guess this can work as simple as crawling `"use client"` files in local directory and put them into `optimizeDeps.entries` instead.)
> fix(rsc): add browser entry to  `optimizeDeps.entries`

- packages/rsc/examples/basic/README.md
- packages/rsc/src/ssr.tsx
I was wondering about the consequence of delaying "prepare destination" to the getter, but I realized we can just kick off early for initial async import as it's not cached.
> perf(rsc): preload client reference deps before non-cached import

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/routes/root.tsx
Part of https://github.com/hi-ogawa/vite-plugins/issues/852.
It looks like this is stackblitz bug, so just hide it from the default demo for now.
> chore(rsc): fix example on stackblitz

- packages/rsc/src/plugin.ts
Got this error when testing it on https://github.com/remix-run/react-router/tree/rsc/playground/rsc-vite
```
11:45:54 AM [vite] Internal server error: Cannot read properties of undefined (reading 'id')
at collectCssByUrl (file:///home/hiroshi/code/others/react-router/node_modules/.pnpm/@hiogawa+vite-rsc@https+++pkg.pr.new+hi-ogawa+vite-plugins+@hiogawa+vite-rsc@854_react-dom@19_a3p7vxeff4cncze72c4kqjdrhi/node_modules/@hiogawa/vite-rsc/dist/plugin.js:613:43)
```
I don't see this locally, but the difference might be due to Vite version (6.2 in react-router, but 6.3 in this repo). Explicitly `moduleGraph.resolveUrl` seems to help, so let's just do that.
> fix(rsc): fix `collectCssByUrl` error

- packages/rsc/examples/react-router/package.json
- packages/rsc/examples/react-router/src/entry.rsc.tsx
- packages/rsc/examples/react-router/src/plugin.ts
- packages/rsc/examples/react-router/src/routes.ts
- packages/rsc/examples/react-router/vite.config.ts
- pnpm-lock.yaml
For now, let's port `routes.ts` processing except their custom `route-module:...` transform.
> chore: tweak react-router example

- packages/rsc/src/plugin.ts
We were only passing over `.css` imports from rsc to browser build, but that probably has some flaws. Let's emit server assets properly and copy the result statically to browser build.
> fix(rsc): emit server assets and copy to client

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/routes/client.module.css
- packages/rsc/examples/basic/src/routes/client.tsx
- packages/rsc/examples/basic/src/routes/root.tsx
- packages/rsc/examples/basic/src/routes/server.module.css
- packages/rsc/src/plugin.ts
Probably we need the same things from https://github.com/hi-ogawa/vite-plugins/pull/346. ~But there's a difference that we currently ignore server build css output and only redirect css files, which seems to break server css module.~ (EDIT: let's address that first https://github.com/hi-ogawa/vite-plugins/pull/861)
_todo_
> fix(rsc): css modules hmr

- packages/rsc/src/plugin.ts
Part of https://github.com/hi-ogawa/vite-plugins/issues/802
```tsx
<TestTemporaryReference
action={(node: React.ReactNode) => {
"use server";
return (
<span>
[server <span>{node}</span>]
</span>
);
}}
/>
```
```
$ pnpm -C packages/rsc/examples/basic build
> @hiogawa/vite-rsc-examples-basic@ build /home/hiroshi/code/personal/vite-plugins/packages/rsc/examples/basic
> vite build --app
vite v6.3.2 building SSR bundle for production...
✓ 5 modules transformed.
✗ Build failed in 71ms
error during build:
[rsc:use-server] "use server" doesn't allow non async function
file: /home/hiroshi/code/personal/vite-plugins/packages/rsc/examples/basic/src/routes/root.tsx:54:18
52:         TestTemporaryReference,
53:         {
54:           action: (node) => {
^
55:             "use server";
56: …
```
> fix(rsc): show invalid transform error with code frame

- packages/rsc/src/extra/rsc.tsx
- packages/rsc/src/extra/ssr.tsx
Related: https://github.com/vercel/next.js/issues/79346
I was noticing the same in some occasions such as
- open https://vite-rsc-basic.hiro18181.workers.dev/
- click "test-client-style-no-ssr", which navigates to https://vite-rsc-basic.hiro18181.workers.dev/?test-client-style-no-ssr
- close tab (e.g. control-w)
- reopen tab (e.g. control-shift-t)
- page shows rsc payload
Actually this reproduces locally by `pnpm -C packages/rsc/examples/basic cf-preview` on http://localhost:8787.
---
This is now fixed by adding `vary: accept` both locally and deployment.
> fix(rsc): add `vary` header to avoid rsc payload on tab re-open

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/e2e/helper.ts
- packages/rsc/examples/basic/playwright.config.ts
- packages/rsc/examples/basic/src/routes/root.tsx
- packages/rsc/examples/basic/src/routes/server.css
- packages/rsc/examples/basic/src/styles.css
This has been quite flaky and I think partly this is because of `createEditor` resets files back and go to next test immediately.
Thinking about we should do either:
- make sure reset is resolved
- remove auto reset for each test and use `afterAll` (👈 going with this)
- restart server after each test
---
It looks like "css hmr server" is flaky regardless. Locally it fails too. Likely it's related to tailwind `styles.css`, but not sure. For now, separating `server.css` helps.
> test: tweak hmr tests

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/routes/client-dep.css
- packages/rsc/examples/basic/src/routes/client-dep.tsx
- packages/rsc/examples/basic/src/routes/client.tsx
- packages/rsc/src/plugin.ts
Found a bug when testing https://github.com/hi-ogawa/vite-plugins/pull/876 and the same issue with transitive css import inside client boundary (EDIT: this is fixed in https://github.com/hi-ogawa/vite-plugins/pull/887). Also client hmr is actually broken for transitive component import.
---
It's very odd that `client-dep.tsx` ends up in rsc module graph. 
```
[hotUpdate] EnvironmentModuleNode {
environment: 'rsc',
url: '/src/routes/client-dep.tsx',
```
Ah, again this is because of tailwind :disappointed: Similar to https://github.com/hi-ogawa/vite-plugins/pull/739, but probably the opposite is happening.
---
Stale virtual ssr css and broken component hmr are different issues as the latter happens only with tailwind. They should be fixed separately.
> fix(rsc): fix non-client-boundary client module hmr in tailwind example

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/src/plugin.ts
The issue is that `addWatchFile(<client-boundary-file>)` only allows invalidating css on client-boundary file change, but this virtual also needs to take into account any transitive css import inside the boundary.
https://github.com/hi-ogawa/vite-plugins/blob/68d6823559e29738fa724c4e092cd0fa265e9640/packages/rsc/src/plugin.ts#L1083-L1084
This fix is for ssr css virtual. The same fix for rsc css virtual will be needed in https://github.com/hi-ogawa/vite-plugins/pull/876.
> fix(rsc): fix stale css import in non-boundary client module

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/e2e/helper.ts
- packages/rsc/examples/basic/playwright.config.ts
- packages/rsc/examples/react-router/playwright.config.ts
Not sure why only macos is being flaky. Is this watcher thing we might need to adjust like this https://github.com/vitejs/vite/blob/c12795522fd95d3535100293f4cf53c53c3f301f/playground/hmr-ssr/__tests__/hmr-ssr.spec.ts#L1090-L1095?
For now, adding a timeout to file editing.
> test: fix flake hmr

- packages/rsc/examples/basic/e2e/basic.test.ts
While testing https://github.com/hi-ogawa/vite-plugins/pull/897, I just noticed `test-server-action-bind-client` breaks with progressive enhancement form.
- got a same error https://github.com/hi-ogawa/reproductions/tree/main/next-rsc-client-action-bind
> test(rsc): test nojs action

- packages/rsc/src/plugin.ts
- follow up https://github.com/hi-ogawa/vite-plugins/pull/899
Now we get a similar error message as Next https://github.com/hi-ogawa/reproductions/tree/main/next-rsc-client-action-bind
```sh
Error: Unexpectedly client reference export 'ActionBindClient' is called on server
```
> fix(rsc): throw on client reference call on server

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/routes/action-bind/server.tsx
- packages/rsc/examples/basic/src/routes/root.tsx
The test were supposed to fail in https://github.com/hi-ogawa/vite-plugins/pull/897 but they are passing because server state is already "true" without resetting properly.
> test(rsc): correctly test nojs action bind

- packages/transforms/src/hoist.test.ts
- packages/transforms/src/hoist.ts
- packages/transforms/src/server-action.ts
- part of https://github.com/hi-ogawa/vite-plugins/issues/881
> feat(transforms): support encrypt closure bind

- packages/rsc/src/rsc.tsx
It looks like tsdown/rolldown handles this in the same way, but probably it should be avoided.
> refactor(rsc): remove self import

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/routes/root.tsx
- packages/rsc/examples/basic/src/routes/serialization/action.tsx
- packages/rsc/examples/basic/src/routes/serialization/client.tsx
- packages/rsc/examples/basic/src/routes/serialization/server.tsx
Initially introduced for action bind encryption (https://github.com/hi-ogawa/vite-plugins/pull/896, https://github.com/hi-ogawa/vite-plugins/pull/905), but now adding an explicit server serialization as test cases.
> test(rsc): add server serialization example

- packages/react-server-next/README.md
- packages/react-server/examples/basic/package.json
- packages/react-server/misc/overrides.mjs
- packages/react-server/package.json
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/runtime/browser.ts
- packages/react-server/src/runtime/ssr.ts
- packages/rsc/examples/basic-core/package.json
- packages/rsc/examples/basic-core/vite.config.ts
- packages/rsc/examples/basic/package.json
- packages/rsc/examples/hono-core/package.json
- packages/rsc/examples/hono-core/vite.config.ts
- packages/rsc/examples/react-router/package.json
- packages/rsc/package.json
- packages/rsc/src/core/plugin.ts
- packages/rsc/src/core/rsc.ts
- packages/rsc/src/plugin.ts
- packages/rsc/src/react/browser.ts
- packages/rsc/src/react/rsc.ts
- packages/rsc/src/react/ssr.ts
- packages/rsc/tsdown.config.ts
- pnpm-lock.yaml
- related https://github.com/hi-ogawa/vite-plugins/pull/851
As usual, why not just do it while `react-server-dom-webpack`?
_todo_
> refactor(rsc)!: vendor react-server-dom

- packages/transforms/src/hoist.test.ts
- packages/transforms/src/hoist.ts
Odd bug found while testing it on react-router's playground. Is it possible that this is scope tracking bug of `periscopic`?
> fix(transforms): fix hoist transform

- packages/rsc/README.md
- packages/rsc/examples/basic-doc/vite.config.ts
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/examples/hono/vite.config.ts
- packages/rsc/examples/react-router/cf/vite.config.ts
- packages/rsc/examples/react-router/vite.config.ts
- packages/rsc/examples/starter/src/framework/entry.rsc.tsx
- packages/rsc/examples/starter/vite.config.ts
- packages/rsc/src/plugin.ts
- packages/rsc/src/rsc.tsx
Part of https://github.com/hi-ogawa/vite-plugins/issues/924
- still breaking because `browser -> client` rename
- ~simplify `getAssetsManifest().bootstrapScriptContent` API~ (later in https://github.com/hi-ogawa/vite-plugins/pull/957)
> refactor!: simplify plugin options in favor of `rollupOptions.input`

- packages/rsc/README.md
- packages/rsc/examples/basic-doc/src/entry.rsc.tsx
- packages/rsc/examples/basic/src/server.ssr.tsx
- packages/rsc/examples/basic/src/server.tsx
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/examples/react-router/app/root.tsx
- packages/rsc/examples/react-router/app/routes/home.tsx
- packages/rsc/examples/react-router/react-router-vite/entry.rsc.node.tsx
- packages/rsc/examples/react-router/react-router-vite/entry.rsc.tsx
- packages/rsc/examples/react-router/vite.config.ts
- packages/rsc/examples/starter/src/framework/entry.rsc.tsx
- packages/rsc/examples/starter/src/root.tsx
- packages/rsc/src/browser.ts
- packages/rsc/src/extra/rsc.tsx
- packages/rsc/src/plugin.ts
- packages/rsc/src/rsc.tsx
- packages/rsc/src/ssr.tsx
- packages/rsc/tsconfig.json
- packages/rsc/types/index.d.ts
Brainstorming for https://github.com/hi-ogawa/vite-plugins/issues/924
```js
import.meta.viteRsc.importSsrEntry("index"); // picks up build.rollupOptions.index
import.meta.viteRsc.importSsr("./entry.ssr.tsx"); // arbitrary
```
Obviously 2nd one is nicer but it would involve discovery techniques. For now, let's start with `importSsrEntry` to make API less implicit than what we have now (i.e. assuming `input.index` everywhere).
Similarly, it's nice to have a way to reference bootstrap script instead of current `getAssetManifest` API. This should probably make injecting hmr preamble slightly easier without virtual module internally.
```js
import.meta.viteRsc.bootstrapBrowserEntry("index")
```
- just making it as a function so maybe there's some option we can squeeze later on without breaking …
> refactor!: rework multi environment API (ssr module)

- packages/rsc/src/plugin.ts
~I'm guessing this might be the cause of  https://github.com/hi-ogawa/rsc-movies/pull/6~
```js
// packages/rsc/examples/basic/dist/rsc/assets/server-DvkQRHkL.js
import __vite_rsc_assets_manifest__ from "./../__vite_rsc_assets_manifest.js";
```
```js
// packages/rsc/examples/basic/dist/rsc/assets/server-DcybpCbQ.js
import __vite_rsc_assets_manifest__ from "../__vite_rsc_assets_manifest.js";
```
> refactor: use `../` instead of `./../` path in output

- packages/rsc/src/plugin.ts
Minimal version of https://github.com/hi-ogawa/vite-plugins/pull/973. Let's hold off `parentPackage` option for now.
Frameworks can use either `@hiogawa/vite-rsc` as peer dep or it's also possible to fix up `optimizeDeps.include` via:
```js
async configEnvironment(name, config, env) {
if (config.optimizeDeps?.include) {
config.optimizeDeps.include = config.optimizeDeps.include.map(name => {
if (name.startsWith("@hiogawa/vite-rsc/")) {
name = `my-framework-package > ${name}`
}
return name;
})
}
```
> refactor: resolve self runtime import instead of `dedupe`

- packages/rsc/src/core/plugin.ts
- packages/rsc/src/core/shared.ts
This is possible after https://github.com/hi-ogawa/vite-plugins/pull/927.
Some package tries to access `__non_webpack_require__` when `__webpack_require__` is defined, so we should avoid surfacing `__webpack_require__` anywhere.
This would help https://github.com/hi-ogawa/rsc-movies/pull/7
---
Sadly, this is breaking `@hiogawa/react-server`. I think https://github.com/hi-ogawa/vite-plugins/pull/927 technically has an issue with dual modules.
We might just want to do the same pre-bundling react deps on ssr just like rsc.
---
This can be technically done when modifying file when vendoring, but it's essentially same.
> fix: transform `__webpack_require__` global

- packages/rsc/examples/starter/README.md
- packages/rsc/examples/starter/vite.config.ts
- scripts/vite-ecosystem-ci.sh
Vite 7 incompatible vite-plugin-inspect was breaking ecosystem-ci.
> chore: remove vite-plugin-inspect from starter

- packages/rsc/README.md
We should use heading so that it can get a link to jump.
> chore: tweak docs heading

- packages/rsc-react-router/src/entry.ssr.tsx
- packages/rsc/README.md
- packages/rsc/examples/react-router/react-router-vite/entry.ssr.tsx
- packages/rsc/examples/starter-cf-single/src/framework/entry.ssr.tsx
- packages/rsc/examples/starter/README.md
- packages/rsc/examples/starter/src/framework/entry.ssr.tsx
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/plugin.ts
- packages/rsc/types/index.d.ts
- packages/rsc/types/virtual.d.ts
Just only this one being virtual is odd, so let's make it `import.meta.viteRsc` API.
> refactor: add `import.meta.viteRsc.loadBootstrapScriptContent`

- packages/rsc/src/plugin.ts
I think we should do this by default (but don't make it build error yet). Found while testing https://github.com/hi-ogawa/waku/pull/2/
> fix: ensure server-only and client-only not externalized

- packages/rsc/examples/react-router/app/routes/home.tsx
- packages/rsc/src/plugin.ts
- packages/transforms/src/wrap-export.test.ts
- packages/transforms/src/wrap-export.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/1044
It's not really sound, but let's just see how far we can get with this:
```js
// input
export default Layout;
// output
export default __vite_rsc_wrap_css__(Layout) // check `typeof Layout === 'function'` internally
```
> feat(rsc,transforms): rsc css transform for default export identifier

- packages/rsc/src/plugin.ts
Fixing the error on waku https://github.com/hi-ogawa/waku/pull/2
```
12:41:27 PM [vite] Internal server error: Unexpected token ''', "['ssr', 'index']" is not valid JSON
Plugin: rsc:load-environment-module
File: /home/hiroshi/code/others/waku/packages/waku/dist/vite-rsc/entry.rsc.js
```
> fix: fix single quote string in `loadModule('ssr', 'index')`

- .github/workflows/pkg-pr-new.yml
- packages/rsc/package.json
- Follow up to https://github.com/hi-ogawa/vite-plugins/pull/1052
I still want prepack command, so locally I can just do `pnpm publish packages/rsc`.
---
Verified https://github.com/pawelblaszczyk5/vite-rsc-experiments works.
> chore: tweak pkg-pr-new

- packages/rsc/src/plugin.ts
- packages/rsc/src/utils/dce.ts
- packages/transforms/src/proxy-export.test.ts
- packages/transforms/src/proxy-export.ts
- required by https://github.com/hi-ogawa/waku/pull/2
The idea is:
```js
"use client"
import { unstable_allowServer as allowServer } from 'waku/client';
import { atom } from 'jotai/vanilla';
import clientDep from "./client-dep" // 🗑️
const local1 = 1;
export const countAtom = allowServer(atom(local1));
const local2 = 2; // 🗑️
export const MyClientComp = () => <div>hey: {local2} {clientDep}</div>  // 🗑️
```
⬇️ custom DCE (implement it in Waku)
```js
"use client"
import { atom } from 'jotai/vanilla';
const local1 = 1;
export const countAtom = atom(local1);
export const MyClientComp = () => { throw new Error('... waku error ...') }
```
⬇️ rsc plugin use client transform with `keep: true`
```js
"use client"
import { atom } from 'jotai/vanilla';
const local1 = 1;
export const countAtom = …
```
> feat(rsc, transforms): support preserving client reference original value

- packages/rsc/examples/basic/src/styles.css
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1075
I wonder whether we should detect this case and just try to ignore by default.
> chore: set tailwind base path to avoid unneeded hmr

- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/examples/starter-e2e/e2e/basic.test.ts
- packages/rsc/src/plugin.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/1101
> fix: copy all server assets to client by default and output `__vite_rsc_encryption_key` to fs directly

- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/src/plugin.ts
Just noticed `dist/client/.vite/manifest.json` is overwritten by `dist/rsc/.vite/manifest.json` when debugging https://github.com/hi-ogawa/vite-plugins/pull/940.
> fix: don't copy vite manifest from rsc to client

- packages/rsc/e2e/fixture.ts
- packages/rsc/examples/basic/package.json
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/package.json
- packages/rsc/src/plugin.ts
- packages/rsc/tsdown.config.ts
- pnpm-lock.yaml
Likely we merge these two together soon. For starter, this needs to be re-exported to align with https://github.com/hi-ogawa/vite-plugins/pull/1121.
> feat: re-export `transformHoistInlineDirective`

- packages/rsc/CHANGELOG.md
- packages/rsc/package.json
This is supposed to be the last release as `@hiogawa/vite-rsc`. A new package with a same content is expected to be published as `@vitejs/plugin-rsc` soon.
> chore: release v0.4.9

- packages/rsc/README.md
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1082
Final brash up to put it on `@vitejs/plugin-rsc` readme. https://github.com/vitejs/vite-plugin-react/pull/521/
> chore: polish readme

- .github/workflows/trigger-nightly.yml
This workflow uses my own [fine-grained personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) with a write access to my folk of react plugin repo https://github.com/hi-ogawa/vite-plugin-react/ to push a commit to a PR https://github.com/vitejs/vite-plugin-react/pull/524, which then triggers pkg.pr.new to release `@vitejs/plugin-rsc` for React canary/experimental channel.
> ci: add workflow to trigger nightly `@vitejs/plugin-rsc` release

- README.md
- packages/rsc/README.md
> chore: deprecate `@hiogawa/vite-rsc` in favor of `@vitejs/plugin-rsc`

- packages/fullstack/src/plugin.ts
I'm not sure if we should bother with this, but why not.
```
$ pnpm -C packages/fullstack/examples/basic/ build
> @hiogawa/vite-plugin-fullstack-examples-basic@ build /home/hiroshi/code/personal/vite-plugins/packages/fullstack/examples/basic
> vite build
vite v7.1.5 building SSR bundle for production...
✓ 8 modules transformed.
dist/ssr/assets/react-CHdo91hT.svg  4.13 kB
dist/ssr/assets/index-ByRLJgsi.css  1.39 kB
dist/ssr/index.js                   3.15 kB
✓ built in 61ms
vite v7.1.5 building for production...
✓ 30 modules transformed.
Generated an empty chunk: "__fallback". 👈👈👈
dist/client/assets/react-CHdo91hT.svg          4.13 kB │ gzip:  2.05 kB
dist/client/assets/entry-B-Rktl8a.css          0.45 kB │ gzip:  0.30 kB
dist/client/assets/__fallback-l0sNRNKZ.js      0.00 kB │ gzip:  0.02 …
```
> fix(fullstack): remove client-fallback from output

- packages/fullstack/examples/react-router/src/framework/entry.server.tsx
- packages/fullstack/examples/react-router/src/routes.ts
- packages/fullstack/examples/vue-router/src/framework/entry.server.ts
- packages/fullstack/examples/vue-router/src/framework/types.d.ts
- packages/fullstack/examples/vue-router/src/routes.ts
- packages/fullstack/examples/vue-router/vite.config.ts
- packages/fullstack/src/plugin.ts
- packages/fullstack/types/index.d.ts
- packages/fullstack/types/query.d.ts
- packages/fullstack/types/shared.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/1207
TODO
- blocked by https://github.com/vitejs/vite-plugin-vue/issues/677
- ~workarounded by allowing `.vue$?assets`, but glob import is not possible `import.meta.glob("*.vue", { query: "?assets" })`.~
- workarounded by `patchVueExclude`
> feat(fullstack): support `?assets` query

- packages/fullstack/e2e/basic.test.ts
- packages/fullstack/e2e/island.test.ts
- packages/fullstack/e2e/react-router.test.ts
- packages/fullstack/e2e/vue-router.test.ts
- packages/fullstack/examples/island/src/framework/entry.server.tsx
- packages/fullstack/src/plugin.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/1233
- closes https://github.com/hi-ogawa/vite-plugins/issues/1237
~Not sure yet. It looks like there are other things going wrong with self importing `?assets=ssr`.~ (EDIT: Other thing is fixed by https://github.com/hi-ogawa/vite-plugins/pull/1240)
> fix(fullstack): avoid `addWatchFile` for virtual invalidation

- packages/fullstack/examples/island/src/framework/entry.server.tsx
- packages/fullstack/examples/island/vite.config.ts
- packages/fullstack/src/plugin.ts
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1243
- Closes https://github.com/hi-ogawa/vite-plugins/pull/1251
If this works, we don't need specific mode like https://github.com/hi-ogawa/vite-plugins/issues/1243
> fix(fullstack): support `cssCodeSplit: false`
