hi-ogawa/vite-plugins

- packages/demo/package.json
- packages/demo/src/routes/layout.tsx
- packages/demo/src/server/index.ts
- pnpm-lock.yaml
> chore: add theme select

- .github/workflows/ci.yml
- .gitignore
- packages/demo/e2e/basic.test.ts
- packages/demo/package.json
- packages/demo/playwright.config.ts
- pnpm-lock.yaml
- vitest.config.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/3
> test: setup e2e

- packages/demo/src/server/adapter-connect.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/15
> fix: fix request path log on dev

- packages/demo/index.html
- packages/demo/package.json
- packages/demo/src/server/index.ts
- packages/demo/vite.config.ts
- packages/vite-expose-index-html/README.md
- packages/vite-expose-index-html/package.json
- packages/vite-expose-index-html/src/index-html.ts
- packages/vite-expose-index-html/src/index.ts
- packages/vite-expose-index-html/src/virtual.d.ts
- packages/vite-expose-index-html/tsconfig.json
- packages/vite-expose-index-html/tsup.config.ts
- packages/vite-index-html-middleware/README.md
- pnpm-lock.yaml
- tsconfig.json
- follow up https://github.com/hi-ogawa/vite-plugins/pull/11
> feat: add `vite-expose-index-html` plugin

- packages/demo/src/routes/dynamic/[id].page.tsx
- packages/demo/src/routes/index.page.tsx
- packages/demo/src/routes/layout.tsx
- packages/demo/src/routes/other.page.tsx
- packages/demo/src/routes/server-data.page.tsx
- packages/demo/src/routes/server-redirect/[id].page.tsx
- packages/demo/src/routes/server-redirect/index.page.tsx
- packages/demo/src/routes/subdir/index.page.tsx
- packages/demo/src/routes/subdir/other.page.tsx
- packages/vite-glob-routes/package.json
- packages/vite-glob-routes/src/react-router-utils.test.ts
- packages/vite-glob-routes/src/react-router-utils.ts
This is to mirror the react-router's convention.
> refactor(glob-routes): rename Page to Component

- package.json
- packages/vite-glob-routes/package.json
- packages/vite-import-index-html/package.json
- pnpm-lock.yaml
Without explicit `devDependencies` in sub packages, it was causing mixed vite version, so I also fixed version for dependent packages.
> chore(deps): update vite

- README.md
- packages/demo/e2e/basic.test.ts
- packages/demo/src/routes/subdir/layout.server.tsx
- packages/demo/src/routes/subdir/other.page.server.tsx
- packages/demo/src/routes/subdir/other.page.tsx
- packages/vite-glob-routes/src/react-router-helper-client.ts
- packages/vite-glob-routes/src/react-router-helper-server.ts
- packages/vite-glob-routes/src/react-router-helper-shared.ts
- packages/vite-glob-routes/src/react-router-utils.test.ts
- packages/vite-glob-routes/src/react-router-utils.ts
- merge base https://github.com/hi-ogawa/vite-plugins/pull/44
> fix: handle loader data request for layout

- package.json
- packages/vite-glob-routes/src/react-router-helper-shared.ts
- pnpm-lock.yaml
very minor possibly useless refactor
> refactor: simplify loader request constants

- packages/demo/e2e/basic.test.ts
- packages/demo/src/client/index.tsx
- packages/demo/src/routes/layout.tsx
Minor but hydration delay was quite notice-able on first load after deploy (i.e. when client assets not cached anywhere yet).
> feat(demo): show spinner while hydrating

- .changeset/README.md
- .changeset/config.json
- .github/workflows/ci.yml
- package.json
- packages/demo/package.json
- packages/vite-glob-routes/CHANGELOG.md
- packages/vite-glob-routes/package.json
- packages/vite-import-index-html/CHANGELOG.md
- packages/vite-import-index-html/package.json
- pnpm-lock.yaml
- cherry picked from https://github.com/hi-ogawa/vite-plugins/pull/69
> chore: setup changeset

- package.json
- packages/demo/vitest.config.ts
- packages/vite-glob-routes/package.json
- vitest.config.ts
Doing it just like https://github.com/hi-ogawa/js-utils/blob/863ff28649674e2f4d4b183b526c4c132709e629/package.json#L10
> chore: split vitest scripts

- packages/demo/package.json
- packages/demo/src/server/session.ts
- pnpm-lock.yaml
- follow up https://github.com/hi-ogawa/js-utils/pull/77
> chore(deps): update tiny-jwt

- packages/demo/package.json
- packages/demo/src/server/session.ts
- pnpm-lock.yaml
Dog-fooding tiny-jwt
- https://github.com/hi-ogawa/js-utils/pull/78
> feat(demo): set session max age

- .changeset/flat-colts-allow.md
- examples/ssr/src/server/ssr.tsx
- packages/demo/src/routes/error.page.tsx
- packages/demo/src/server/ssr.tsx
- packages/vite-glob-routes/package.json
- packages/vite-glob-routes/src/index.ts
- packages/vite-glob-routes/src/react-router/misc.ts
- packages/vite-glob-routes/src/react-router/server-helper.ts
- packages/vite-glob-routes/tsup.config.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/84
> feat(glob-routes): support user callback on loader exception

- packages/vite-glob-routes/package.json
- packages/vite-import-dev-server/package.json
```sh
sort-package-json $(pnpm ls --filter '*' --depth -1 --json | jq -r '.[] | .path' | xargs -I '{}' echo '{}/package.json')
```
> chore: sort package json

- packages/demo/package.json
- packages/demo/src/routes/layout.tsx
- packages/demo/src/routes/loader-data.page.tsx
- packages/demo/src/routes/session/login.page.tsx
- packages/demo/src/utils/react-query-utils.tsx
- packages/demo/src/utils/toast.tsx
- pnpm-lock.yaml
For the sake of dog-fooding...
> refactor(demo): replace deps with own packages

- examples/spa/misc/vercel/build.sh
- examples/spa/vite.config.ts
- examples/ssr/misc/vercel-edge/build.sh
- examples/ssr/misc/vercel/build.sh
- examples/ssr/vite.config.ts
- packages/demo/src/server/ssr.tsx
- packages/demo/vite.config.ts
- Preparing for https://github.com/hi-ogawa/vite-plugins/issues/113
> chore: use explicit path for vite manifest

- .github/workflows/ci.yml
- packages/vite-node-miniflare/README.md
- packages/vite-node-miniflare/demo/src/worker-entry.ts
- packages/vite-node-miniflare/demo/vite.config.ts
- packages/vite-node-miniflare/package.json
- packages/vite-node-miniflare/src/client/polyfills/node-fs.ts
- packages/vite-node-miniflare/src/client/worker-entry.ts
- packages/vite-node-miniflare/src/server/plugin.ts
- packages/vite-node-miniflare/src/server/vite-node.ts
Also added quick-and-dirty `debug` option.
> feat(vite-node-miniflare): improve module invalidation

- packages/vite-node-miniflare/demo-react/vite.config.ts
- packages/vite-node-miniflare/demo/vite.config.ts
- packages/vite-node-miniflare/package.json
- packages/vite-node-miniflare/src/client/polyfills/README.md
- packages/vite-node-miniflare/src/client/polyfills/debug.ts
- packages/vite-node-miniflare/src/client/vite-node.ts
- packages/vite-node-miniflare/src/client/worker-entry.ts
- packages/vite-node-miniflare/src/server/plugin.ts
- packages/vite-node-miniflare/tsup.config.ts
- part of https://github.com/hi-ogawa/vite-plugins/issues/127
> feat(vite-node-miniflare): support `vite-node/client` debug

- examples/ssr/e2e/basic.test.ts
- examples/ssr/src/routes/hello.api.ts
- examples/ssr/src/routes/layout.tsx
While doing https://github.com/hi-ogawa/vite-plugins/pull/132, I just noticed the example was only doing GET requests. Why not including POST too.
> test: add POST API request example

- packages/vite-node-miniflare/src/server/plugin.ts
> refactor(vite-node-miniflare): cleanup indent

- packages/vite-glob-routes/src/index.ts
- packages/vite-import-dev-server/src/index.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/131
> refactor(glob-routes): follow virtual module convention

- packages/vite-node-miniflare/examples/basic/e2e/basic.test.ts
- packages/vite-node-miniflare/examples/basic/package.json
- packages/vite-node-miniflare/examples/basic/src/app.tsx
- pnpm-lock.yaml
Verifying
- https://github.com/hi-ogawa/js-utils/pull/197
> chore(deps): update tiny-react

- packages/vite-plugin-ssr-middleware/README.md
- packages/vite-plugin-ssr-middleware/examples/react/README.md
- packages/vite-plugin-ssr-middleware/examples/react/index.html
- packages/vite-plugin-ssr-middleware/examples/react/package.json
- packages/vite-plugin-ssr-middleware/examples/react/src/app.tsx
- packages/vite-plugin-ssr-middleware/examples/react/src/entry-client.tsx
- packages/vite-plugin-ssr-middleware/examples/react/src/entry-server.tsx
- packages/vite-plugin-ssr-middleware/examples/react/tsconfig.json
- packages/vite-plugin-ssr-middleware/examples/react/vite.config.ts
- packages/vite-plugin-ssr-middleware/src/plugin.ts
- pnpm-lock.yaml
Closes https://github.com/hi-ogawa/vite-plugins/issues/158
> feat(vite-plugin-ssr-middleware): expose `ViteDevServer`

- packages/vite-node-miniflare/examples/basic/index.html
- packages/vite-node-miniflare/examples/basic/src/worker-entry.ts
- packages/vite-node-miniflare/examples/react-router/index.html
- packages/vite-node-miniflare/examples/react-router/src/server/ssr.tsx
- packages/vite-node-miniflare/examples/react-router/tsconfig.json
- packages/vite-node-miniflare/examples/react/index.html
- packages/vite-node-miniflare/examples/react/src/worker-entry.tsx
- packages/vite-node-miniflare/examples/react/tsconfig.json
- packages/vite-node-miniflare/examples/remix/app/worker-entry.ts
- packages/vite-node-miniflare/src/client/worker-entry.ts
- packages/vite-node-miniflare/src/index.ts
- packages/vite-node-miniflare/src/server/plugin.ts
- packages/vite-node-miniflare/src/shared.ts
Removing unnecessary indirection...
> refactor(vite-node-miniflare): minor refactoring

- .github/workflows/ci.yml
- packages/react-server/README.md
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/components/header.tsx
- packages/react-server/examples/basic/src/lib/shared.tsx
- packages/react-server/examples/basic/src/routes/test/action/action-client-import-only.tsx
- packages/react-server/examples/basic/src/routes/test/action/action.tsx
- packages/react-server/examples/basic/src/routes/test/action/client.tsx
- packages/react-server/examples/basic/src/routes/test/action/page.tsx
- packages/react-server/examples/basic/vite.config.ts
- pnpm-lock.yaml
> feat(react-server): server reference in rsc

- .npmrc
- packages/react-server/README.md
- packages/react-server/examples/starter/README.md
- packages/react-server/examples/starter/package.json
- pnpm-lock.yaml
This would allow easier template setup, but testing might be trickier?
> chore: use latest in example

- packages/react-server/examples/basic/src/entry-server.tsx
- packages/react-server/examples/basic/vite.config.ts
- packages/react-server/examples/starter/src/entry-server.tsx
- packages/react-server/package.json
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/lib/debug.ts
- packages/react-server/src/lib/ssr.tsx
- packages/react-server/src/plugin/index.ts
Added quick-and-dirty debug utility. Also experimented with simple http logger.
> chore(react-server): cleanup debug log

- packages/react-server/examples/basic/vite.config.ts
- packages/react-server/examples/starter/package.json
- packages/react-server/examples/starter/src/entry-server.tsx
- packages/react-server/examples/starter/vite.config.ts
- packages/vite-plugin-ssr-middleware/examples/react/vite.config.ts
- packages/vite-plugin-ssr-middleware/package.json
- packages/vite-plugin-ssr-middleware/src/plugin.ts
- pnpm-lock.yaml
Follow up to https://github.com/hi-ogawa/vite-plugins/pull/181
> feat(ssr-middleware): add `vitePluginLogger`

- .github/workflows/ci.yml
- package.json
- packages/react-server/README.md
- packages/react-server/examples/basic/README.md
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/routes/test/other/client.tsx
- packages/react-server/examples/basic/src/routes/test/other/page.tsx
- packages/react-server/examples/basic/tsconfig.json
- packages/react-server/examples/basic/vite.config.ts
- packages/react-server/examples/starter/README.md
- packages/react-server/examples/starter/tsconfig.json
- packages/react-server/misc/test.sh
- packages/react-server/package.json
- pnpm-lock.yaml
Follow up to https://github.com/hi-ogawa/vite-plugins/pull/186
This is important to not miss Vite's linked deps specific behavior.
> test(react-server): test fresh install

- packages/react-server/src/plugin/index.ts
I don't think this `ssr.optimizeDeps.include` is necessary?
It should be fine if CI passes.
> refactor(react-server): simplify `rscConfig`

- packages/react-server/examples/basic/package.json
- pnpm-lock.yaml
I just noticed the github icon is gone...
> fix: fix icon

- packages/react-server/examples/basic/src/routes/demo/waku_02/[pokemon]/error.tsx
- packages/react-server/examples/basic/src/routes/demo/waku_02/[pokemon]/layout.tsx
- packages/react-server/examples/basic/src/routes/demo/waku_02/[pokemon]/page.tsx
- packages/react-server/examples/basic/src/routes/layout.tsx
- packages/react-server/examples/basic/src/routes/test/error.tsx
- packages/react-server/examples/basic/src/routes/test/error/server/page.tsx
- packages/react-server/examples/basic/src/routes/test/head/page.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/examples/basic/src/routes/test/other/page.tsx
- packages/react-server/package.json
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/lib/components/error-boundary.tsx
- packages/react-server/src/lib/router.tsx
- packages/react-server/src/server.ts
Small renaming and cleanup props
> refactor(react-server): tweak `PageProps`

- packages/react-server/package.json
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/server-component/stream-script.tsx
- pnpm-lock.yaml
We can figure out more sophisticated things later.
> refactor(react-server): replace rsc-html-stream

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/head/page.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/examples/basic/src/routes/test/other/page.tsx
- packages/react-server/examples/basic/src/routes/test/transition-action/_action.tsx
- packages/react-server/examples/basic/src/routes/test/transition-action/_client.tsx
- packages/react-server/examples/basic/src/routes/test/transition-action/page.tsx
- packages/react-server/examples/basic/src/routes/test/transition/_client.tsx
- packages/react-server/examples/basic/src/routes/test/transition/layout.tsx
Separating some example bugs found in https://github.com/hi-ogawa/vite-plugins/pull/231
> test(react-server): fix examples

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/redirect/_action.tsx
- packages/react-server/examples/basic/src/routes/test/redirect/layout.tsx
- packages/react-server/examples/basic/src/routes/test/redirect/page.tsx
- packages/react-server/package.json
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/react-server.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/utils.tsx
- packages/react-server/src/lib/client/error-boundary.tsx
- packages/react-server/src/lib/error.tsx
This looks like a different monster, so let's do this separate from
- https://github.com/hi-ogawa/vite-plugins/pull/243
TODO
> feat(react-server): server action redirect

- misc/changelog.mts
- package.json
- packages/react-server/CHANGELOG.md
- pnpm-lock.yaml
- follow up to https://github.com/hi-ogawa/vite-plugins/pull/258
> chore: add changelog cli

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/playwright.config.ts
- packages/react-server/examples/basic/src/components/counter.tsx
Let's add failing hmr case found in
- https://github.com/hi-ogawa/vite-environment-examples/pull/12
> test: more hmr tests

- packages/react-server/examples/basic/e2e/basic.test.ts
Copied from https://github.com/hi-ogawa/vite-plugins/pull/282
> test(react-server): test server action after client render

- packages/react-server/examples/basic/src/routes/test/action/_action.tsx
- packages/react-server/src/plugin/ast-utils.ts
- packages/react-server/src/plugin/index.ts
Found during https://github.com/hi-ogawa/vite-environment-examples/pull/18
> fix(react-server): fix server action `const/let` transform

- packages/react-server/src/features/server-action/plugin.tsx
- packages/react-server/src/features/use-client/plugin.ts
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/plugin/utils.tsx
Moving some code from `src/plugin/index.ts` to `src/features/xxx/plugin.ts`
> refactor(react-server): organize features

- packages/ssr-css/src/plugin.ts
I remembered virtual css gets stale and invalidating on each request is a easy way to get around, similar to what I did for react server css:
https://github.com/hi-ogawa/vite-plugins/blob/3fc6c5c1169f77f3a76d758a24112632da86439c/packages/react-server/src/entry/server.tsx#L110-L115
> fix(ssr-css): invalidate virtual module on each direct request

- packages/error-overlay/examples/basic/src/entry-server.tsx
- packages/vite-glob-routes/examples/demo/src/server/ssr.tsx
- packages/vite-glob-routes/examples/ssr/src/server/ssr.tsx
- packages/vite-node-miniflare/examples/basic/src/worker-entry.ts
- packages/vite-node-miniflare/examples/react-router/src/server/ssr.tsx
- packages/vite-node-miniflare/examples/react/src/worker-entry.tsx
- packages/vite-plugin-simple-hmr/examples/react/src/entry-server.tsx
- packages/vite-plugin-ssr-middleware/examples/react/src/entry-server.tsx
Same as
- https://github.com/hi-ogawa/vite-environment-examples/pull/66
> fix: fix html replace

- packages/react-server/src/features/server-action/plugin.tsx
- packages/react-server/src/features/use-client/plugin.ts
Some trivial PR to test graphite
> refactor(react-server): use constants

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/components/nav-menu.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/plugin.ts
- packages/react-server/src/lib/client/link.tsx
- packages/react-server/src/lib/client/router.tsx
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/utils/escape.ts
- supersedes https://github.com/hi-ogawa/vite-plugins/pull/257
> feat(react-server): preload client assets on navigation

- .github/workflows/ci.yml
- packages/react-server/examples/prerender/e2e/basic.test.ts
- packages/react-server/examples/prerender/src/routes/posts/[id]/page.tsx
- packages/react-server/examples/prerender/vite.config.ts
> chore: prerender and ssr hybrid example

- packages/react-server/examples/prerender/misc/vercel/.vc-config.json
- packages/react-server/examples/prerender/misc/vercel/build.sh
- packages/react-server/examples/prerender/misc/vercel/config.json
- packages/react-server/examples/prerender/package.json
- packages/react-server/examples/prerender/src/adapters/vercel-edge.ts
Forgot to push to the last PR
- https://github.com/hi-ogawa/vite-plugins/pull/364
> chore: vercel hybrid deploy (forgot to push)

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/other/_client.tsx
- packages/react-server/examples/basic/src/routes/test/other/page.tsx
- packages/react-server/src/lib/client/link.tsx
- closes https://github.com/hi-ogawa/vite-plugins/issues/367
> fix: merge Link props handlers

- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/adapters/node.ts
- packages/react-server/examples/starter/package.json
- packages/react-server/examples/starter/src/adapters/node.ts
- packages/vite-glob-routes/examples/demo/src/server/install-polyfill.ts
- pnpm-lock.yaml
Let's dog food `webToNodeHandler` more.
> chore(deps): replace hattip with utils-node

- .npmrc
- package.json
- pnpm-lock.yaml
- closes https://github.com/hi-ogawa/vite-plugins/issues/321
> chore(deps): update pnpm v9.2.0

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/_client.tsx
- packages/react-server/examples/basic/src/routes/test/action/_action.tsx
- packages/react-server/examples/basic/src/routes/test/action/_client.tsx
Looks fairly convoluted to support both js and no-js.
> chore: add `useOptimistic` demo

- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/assets/plugin.ts
- packages/react-server/src/features/assets/shared.ts
- packages/react-server/src/plugin/index.ts
Spotted an obvious bug. Cherry picked from https://github.com/hi-ogawa/vite-plugins/pull/278
> fix: fix css virtual module invalidation

- .github/workflows/ci.yml
Splitting `test-react-server` job to reduce total duration to half
> ci: split tests

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/misc/cloudflare-workers/build.sh
- packages/react-server/examples/basic/misc/cloudflare-workers/wrangler.toml
- packages/react-server/examples/basic/misc/vercel/build.sh
- packages/react-server/examples/basic/src/_enable-react-cache.ts
- packages/react-server/examples/basic/src/entry-react-server.tsx
- packages/react-server/examples/basic/src/routes/test/cache/layout.tsx
- packages/react-server/examples/basic/src/routes/test/cache/page.tsx
- packages/react-server/examples/basic/src/routes/test/layout.tsx
- packages/react-server/examples/starter/misc/cloudflare-workers/build.sh
- https://react.dev/reference/react/cache
> chore: add `React.cache` example

- package.json
- packages/react-server/CHANGELOG.md
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/next/package.json
- packages/react-server/examples/prerender/package.json
- packages/react-server/examples/starter/package.json
- packages/react-server/package.json
- pnpm-lock.yaml
- (supersedes) close https://github.com/hi-ogawa/vite-plugins/pull/399/
> chore(deps): update react 19.0.0-rc-c21bcd627b-20240624

- packages/react-server/examples/next/app/actions/README.md
- packages/react-server/examples/next/app/actions/client/actions.ts
- packages/react-server/examples/next/app/actions/client/layout.tsx
- packages/react-server/examples/next/app/actions/client/page.tsx
- packages/react-server/examples/next/app/actions/server/actions-3.ts
- packages/react-server/examples/next/app/actions/server/actions.ts
- packages/react-server/examples/next/app/actions/server/counter.tsx
- packages/react-server/examples/next/app/actions/server/page.tsx
- packages/react-server/examples/next/e2e/basic.test.ts
- packages/react-server/examples/next/e2e/helper.ts
Part of https://github.com/hi-ogawa/vite-plugins/issues/406
> test(next): add actions e2e

- packages/react-server-next/package.json
Probably unnecessary to have this strictness for now
> fix(next): relax peer deps

- packages/react-server-next/src/vite/index.ts
It just looks bothering, so let me move it a bit.
> refactor: move code

- packages/react-server-next/bin/cli.js
- Part of https://github.com/hi-ogawa/vite-plugins/issues/434
> feat(next): auto setup vite.config.ts

- packages/react-server-next/package.json
- packages/react-server-next/src/vite/index.ts
- packages/react-server/examples/next/app/layout.tsx
- pnpm-lock.yaml
- Part of https://github.com/hi-ogawa/vite-plugins/issues/434
> feat(next): auto setup vite-tsconfig-paths

- packages/react-server/examples/next/app/actions/header/actions.ts
- packages/react-server/examples/next/app/actions/header/page.tsx
- packages/react-server/examples/next/app/actions/header/ui.tsx
- packages/react-server/examples/next/app/actions/header/validator.ts
- packages/react-server/examples/next/app/actions/mutate-cookie/page-2/page.tsx
- packages/react-server/examples/next/app/actions/mutate-cookie/page.tsx
- packages/react-server/examples/next/app/actions/redirect-target/page.tsx
- packages/react-server/examples/next/app/test/page.tsx
For now, let's just copy some files and play with it manually since we have tests in `examples/basic` already.
> test(next): add `headers` and `cookies` tests

- packages/react-server-next/src/vite/entry-browser.tsx
- packages/react-server-next/src/vite/entry-server.tsx
- packages/react-server-next/src/vite/index.ts
- packages/react-server-next/tsup.config.ts
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/adapters/cf.ts
- packages/react-server/examples/basic/src/adapters/node.ts
- packages/react-server/examples/basic/src/adapters/vercel-edge.ts
- packages/react-server/examples/basic/src/entry-client.tsx
- packages/react-server/examples/basic/src/entry-server.tsx
- packages/react-server/examples/basic/vite.config.ts
- packages/react-server/examples/prerender/src/adapters/cf.ts
- packages/react-server/examples/prerender/src/adapters/node.ts
- packages/react-server/examples/prerender/src/adapters/vercel-edge.ts
- packages/react-server/examples/prerender/src/entry-client.tsx
- packages/react-server/examples/prerender/src/entry-react-server.tsx
- packages/react-server/examples/prerender/src/entry-server.tsx
- packages/react-server/examples/prerender/src/routes/layout.tsx
- packages/react-server/examples/starter/src/adapters/cf.ts
- packages/react-server/examples/starter/src/adapters/node.ts
- packages/react-server/examples/starter/src/entry-client.tsx
- packages/react-server/examples/starter/src/entry-react-server.tsx
- packages/react-server/examples/starter/src/entry-server.tsx
- packages/react-server/examples/starter/src/routes/layout.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/plugin/index.ts
It looks working alright on Next compat, so let's do it on core examples too.
Not gonna lie default entries feel very convenient.
> feat!: default entries for browser and server build

- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/entry/ssr.tsx
- packages/react-server/src/features/router/client.tsx
- packages/react-server/src/features/router/tree.ts
- packages/react-server/src/features/router/utils.tsx
- packages/react-server/src/features/server-action/client.tsx
Initially I called everything "layout", but the meaning has changed quite a bit now...
> refactor: rename "layout" to "flight"

- packages/react-server/examples/basic/src/routes/test/revalidate/layout.tsx
- packages/react-server/examples/basic/src/routes/test/revalidate/redirect/page.tsx
- packages/react-server/src/entry/browser.tsx
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/features/server-action/redirect.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/543
> fix: fix action `redirect` with `revalidatePath`

- packages/react-server/src/entry/server.tsx
- packages/react-server/src/plugin/virtual.d.ts
Cherry-picking one idea from https://github.com/hi-ogawa/vite-plugins/pull/553
> refactor: type `virtual:server-routes`

- packages/react-server-next/package.json
- packages/react-server-next/src/compat/font/_noop.tsx
- packages/react-server-next/src/compat/font/google.tsx
- packages/react-server-next/src/compat/font/local.tsx
- required by https://github.com/hi-ogawa/next-learn/pull/1
> fix(next): more compat exports

- .github/workflows/ci.yml
- .github/workflows/pkg-pr-new.yml
Integrating https://github.com/stackblitz-labs/pkg.pr.new
> ci: setup pkg.pr.new

- packages/react-server/examples/next/e2e/basic.test.ts
- packages/react-server/examples/next/middleware.ts
- packages/react-server/src/entry/server.tsx
- packages/react-server/src/entry/ssr.tsx
- packages/react-server/src/features/next/cookie.ts
- packages/react-server/src/features/next/middleware.ts
- packages/react-server/src/features/request-context/server.ts
- packages/react-server/src/features/router/api-route.ts
- packages/react-server/src/features/server-action/redirect.ts
- packages/react-server/src/features/server-action/server.tsx
Minor restructuring to generalize mutating response headers from request context.
> refactor: rework `RequestContext`

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/src/routes/test/redirect/layout.tsx
- packages/react-server/examples/basic/src/routes/test/redirect/page.tsx
- packages/react-server/examples/basic/src/routes/test/redirect/suspense/page.tsx
- packages/react-server/examples/next/app/navigation/redirect/suspense/page.js
I skipped this one previously, but it's working now probably thanks to https://github.com/hi-ogawa/vite-plugins/pull/531.
I feel this is going to break easily for example by https://github.com/hi-ogawa/vite-plugins/pull/566, so let's make sure having tests.
> test: add suspense redirect test

- .github/workflows/ci.yml
- package.json
- packages/react-server-next/package.json
- packages/react-server-next/src/vite/index.ts
- packages/react-server/examples/basic/vite.config.ts
- packages/react-server/src/plugin/index.ts
- pnpm-lock.yaml
- closes https://github.com/hi-ogawa/vite-plugins/issues/535
> feat: support plugin-react-swc + perf(next): use plugin-react-swc

- packages/react-server/src/plugin/index.ts
Forgot to remove this after
- https://github.com/hi-ogawa/vite-plugins/pull/573
> fix: remove unneecssary `optimizeDeps.include`

- .github/workflows/pkg-pr-new.yml
Comment feels a bit noisy. It provides a summary from app https://github.com/hi-ogawa/vite-plugins/pull/584/checks?check_run_id=27713070518 and that looks enough.
> ci: pkg-pr-new comment off

- packages/react-server-next/src/vite/adapters/vercel/build.ts
- packages/react-server/examples/prerender/misc/vercel/build.js
- packages/react-server/examples/prerender/src/routes/layout.tsx
- packages/react-server/src/features/prerender/plugin.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/586
- https://demo-rsc-prerender.vercel.app/
> fix: fix deployment with pre-rendered root path

- package.json
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/vite-node-miniflare/examples/basic/package.json
- packages/vite-node-miniflare/examples/react-router/package.json
- packages/vite-node-miniflare/examples/react/package.json
- packages/vite-node-miniflare/examples/remix/package.json
- packages/vite-node-miniflare/package.json
- pnpm-lock.yaml
For now, let's disable streaming related test on cloudflare (cf. https://github.com/hi-ogawa/vite-plugins/pull/523).
I remembered I had this "non repro" https://github.com/hi-ogawa/reproductions/tree/main/wrangler-stream-response. we should try actual repro this time and submit an issue on workers-sdk. 
---
reported to wrangler https://github.com/cloudflare/workers-sdk/issues/6577
> chore(deps): update cloudflare deps

- packages/error-overlay/examples/basic/package.json
- packages/pre-bundle-new-url/package.json
- packages/react-server-next/package.json
- packages/react-server/package.json
- packages/server-asset/package.json
- related https://github.com/hi-ogawa/js-utils/pull/267
I haven't run this for a while, so doing it now.
```sh
pnpm dlx @hiogawa/sort-package-json $(pnpm ls --filter '*' --depth -1 --json | jq -r '.[] | .path')
```
> chore: sort package.json

- packages/react-server/src/features/assets/plugin.ts
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/plugin/utils.tsx
Picking changes from https://github.com/hi-ogawa/vite-plugins/pull/297 since these changes are technically required for Vite 5 as well.
> fix: apply changes from vite 6 compat

- packages/vite-node-miniflare/examples/basic/src/worker-entry.ts
- packages/vite-node-miniflare/examples/basic/tsconfig.json
- packages/vite-node-miniflare/examples/basic/vite.config.ts
- packages/vite-node-miniflare/examples/react-router/src/server/ssr.tsx
- packages/vite-node-miniflare/examples/react-router/vite.config.ts
- packages/vite-node-miniflare/examples/react/src/worker-entry.tsx
- packages/vite-node-miniflare/examples/react/vite.config.ts
- packages/vite-node-miniflare/examples/remix/app/worker-entry.ts
- packages/vite-node-miniflare/examples/remix/vite.config.ts
Picking up trivial changes from https://github.com/hi-ogawa/vite-plugins/pull/594
> chore(vite-node-miniflare): simplify examples

- packages/react-server/src/plugin/utils.tsx
> fix: wrong parentheses in `vitePluginSilenceDirectiveBuildWarning`

- packages/react-server/examples/basic/misc/cf/wrangler.toml
CI failure is from https://github.com/hi-ogawa/vite-plugins/pull/655
> chore: update cf assets config

- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/adapters/cf.ts
- workaround https://github.com/cloudflare/workers-sdk/issues/6577
> chore: workaround wrangler dev streaming issue

- package.json
- packages/react-server-next/package.json
- packages/react-server/examples/basic/misc/cf/wrangler.toml
- packages/react-server/examples/cloudflare/package.json
- packages/vite-node-miniflare/examples/basic/package.json
- packages/vite-node-miniflare/examples/react-router/package.json
- packages/vite-node-miniflare/examples/react/package.json
- packages/vite-node-miniflare/examples/remix/package.json
- packages/vite-node-miniflare/package.json
- pnpm-lock.yaml
It looks like I need to update wrangler to use new `assets` config https://developers.cloudflare.com/workers/static-assets/binding/
> chore(deps): update wrangler

- packages/react-server/examples/basic/deps/cjs/README.md
- packages/react-server/examples/basic/deps/cjs/client-dep.cjs
- packages/react-server/examples/basic/deps/cjs/client.js
- packages/react-server/examples/basic/deps/cjs/package.json
- packages/react-server/examples/basic/deps/cjs/server.js
- packages/react-server/examples/basic/deps/cjs/server2.js
- packages/react-server/examples/basic/deps/context/README.md
- packages/react-server/examples/basic/deps/context/client.js
- packages/react-server/examples/basic/deps/context/package.json
- packages/react-server/examples/basic/deps/context/server.js
- packages/react-server/examples/basic/deps/context/server2.js
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/basic/src/routes/test/deps/examples/cjs/page.tsx
- packages/react-server/examples/basic/src/routes/test/deps/examples/cjs2/page.tsx
- packages/react-server/examples/basic/src/routes/test/deps/examples/context/page.tsx
- packages/react-server/examples/basic/src/routes/test/deps/examples/context2/page.tsx
- packages/react-server/examples/basic/src/routes/test/deps/layout.tsx
- pnpm-lock.yaml
- related https://github.com/hi-ogawa/vite-plugins/issues/379
- only self reference one works as expected
> chore: add more test packages

- package.json
- packages/pre-bundle-new-url/package.json
- packages/react-server-next/package.json
- packages/react-server/examples/basic/package.json
- packages/react-server/package.json
- packages/server-asset/package.json
- packages/transforms/package.json
- packages/vite-glob-routes/examples/ssr/package.json
- packages/vite-null-export/package.json
- packages/vite-plugin-simple-hmr/package.json
- pnpm-lock.yaml
Runtime dep `vitefu` was missing Vite 6 peer dep. Let's update all of them now.
> chore(deps): update deps 2025-01-23

- packages/react-server-next/CHANGELOG.md
- packages/react-server/CHANGELOG.md
Forgot to update the date in the last PR https://github.com/hi-ogawa/vite-plugins/pull/662
> chore: fix changelog date

- .github/actions/setup/action.yml
- packages/pre-bundle-new-url/examples/basic/tsconfig.json
- packages/react-server-next/src/compat/og.tsx
- packages/react-server/src/features/prerender/plugin.ts
- packages/react-server/src/plugin/index.ts
Fixing my plugin side issues found in https://github.com/hi-ogawa/vite-plugins/pull/673 separately
> fix: misc fix from #673

- packages/react-server/src/plugin/index.ts
Not a proper API, but I think this is fine for now.
> fix: skip write files on scan build

- packages/react-server/src/features/client-component/server.tsx
- packages/react-server/src/features/client-component/ssr.tsx
- packages/react-server/src/features/server-action/server.tsx
- packages/react-server/src/plugin/index.ts
- packages/react-server/src/types/react.ts
Copying https://github.com/hi-ogawa/vite-environment-examples/pull/156
> refactor: use async server reference

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/action.tsx
- packages/rsc/src/core/client-browser.ts
- packages/rsc/src/core/client-ssr.ts
- packages/rsc/src/core/server.ts
- packages/rsc/src/core/shared.ts
I remembered this was the old idea, which should work fine now.
> fix(rsc): fix promise cache invalidation

- package.json
- packages/react-server/examples/basic/e2e/basic.test.ts
- packages/react-server/examples/basic/package.json
- packages/react-server/examples/custom-out-dir/package.json
- packages/react-server/examples/next/package.json
- packages/react-server/examples/prerender/package.json
- pnpm-lock.yaml
Okay, the CI failure is due to latest playwright...
- closes https://github.com/users/hi-ogawa/projects/4/views/1?pane=issue&itemId=107197563
I thought this is a breaking change, but probably they can say it's a legitimate fix.
> chore(deps): update playwright

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/counter.tsx
- packages/rsc/examples/basic/src/server.tsx
- packages/rsc/examples/basic/src/styles.css
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/examples/react-router/src/entry.ssr.tsx
- packages/rsc/examples/react-router/src/routes/root.tsx
- packages/rsc/examples/react-router/src/styles.css
- packages/rsc/examples/react-router/vite.config.ts
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/plugin.ts
- packages/rsc/src/ssr.ts
- packages/rsc/src/types/index.ts
- packages/rsc/src/types/virtual.d.ts
- closes https://github.com/hi-ogawa/vite-plugins/issues/730
let's call this "css support" :upside_down_face: 
_todo_
> feat(rsc): support css entry

- packages/rsc/README.md
- packages/rsc/examples/hono-core/src/client.tsx
- packages/rsc/examples/hono-core/src/server.tsx
- Closes https://github.com/hi-ogawa/vite-plugins/issues/746
> chore(rsc): doc in readme

- packages/rsc/examples/react-router/src/entry.browser.tsx
There was unnecessary `callServer` there.
> chore(rsc): tweak example

- packages/rsc/README.md
- packages/rsc/examples/basic-core/src/browser.tsx
- packages/rsc/examples/basic-core/src/routes/action.tsx
- packages/rsc/examples/basic-core/src/routes/root.tsx
- packages/rsc/examples/basic-core/src/rsc.tsx
- packages/rsc/examples/basic-core/src/ssr.tsx
- packages/rsc/examples/basic-core/vite.config.ts
Just duplicating more things but why not...
> chore(rsc): tweak basic-core

- packages/rsc/src/core/browser.ts
- packages/rsc/src/core/rsc.ts
- packages/rsc/src/core/shared.ts
- packages/rsc/src/core/ssr.ts
- packages/rsc/src/plugin.ts
- pnpm-lock.yaml
Minor refactoring to ease https://github.com/hi-ogawa/vite-plugins/pull/768
> refactor(rsc): minor

- packages/react-server/examples/basic/e2e/basic.test.ts
check picked from https://github.com/hi-ogawa/vite-plugins/pull/772
> test: tweak test for react experimental

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/basic/src/counter.tsx
- packages/rsc/examples/basic/src/server.tsx
- packages/rsc/src/extra/browser.tsx
- packages/rsc/src/extra/rsc.tsx
- packages/rsc/src/react/browser.ts
- packages/rsc/src/react/rsc.ts
- packages/rsc/src/react/ssr.ts
- https://github.com/facebook/react/pull/28564
- learn API from Parcel's rsc helper https://github.com/parcel-bundler/parcel/tree/v2/packages/utils/rsc
_todo_
> feat(rsc): support temporary references

- packages/react-server/src/features/client-component/plugin.ts
- packages/react-server/src/features/server-action/plugin.tsx
- packages/rsc/src/plugin.ts
- packages/transforms/src/hoist.test.ts
- packages/transforms/src/hoist.ts
- packages/transforms/src/proxy-export.test.ts
- packages/transforms/src/proxy-export.ts
- packages/transforms/src/server-action.ts
- packages/transforms/src/wrap-export.test.ts
- packages/transforms/src/wrap-export.ts
- required by https://github.com/hi-ogawa/vite-plugins/issues/780
> refactor(transforms)!: tweak API

- tsconfig.base.json
This is a bit of pain and I don't see much benefit.
> chore: relax tsconfig `noImplicitReturns`

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/react-router/e2e/basic.test.ts
Adding a test for https://github.com/hi-ogawa/vite-plugins/pull/814
> test(rsc): test react-router ssr modulepreload

- packages/rsc/src/plugin.ts
- workaround for https://github.com/vitejs/vite/issues/19975
- closes https://github.com/hi-ogawa/vite-plugins/issues/742
> fix(rsc): wrap virtual to  workaround module runner entry issues

- .github/workflows/ci.yml
This doesn't help much though, why not?
> ci: save test-results

- packages/rsc/examples/react-router/e2e/basic.test.ts
- packages/rsc/examples/react-router/e2e/helper.ts
- packages/rsc/examples/react-router/src/entry.browser.tsx
- packages/rsc/examples/react-router/src/routes/root.client.tsx
- packages/rsc/examples/react-router/src/routes/root.tsx
> chore(rsc): server hmr on react-router

- .github/actions/setup/action.yml
- .github/workflows/ci.yml
- .npmrc
- packages/rsc/src/plugin.ts
- Closes https://github.com/hi-ogawa/vite-plugins/issues/883
> fix(rsc): support Windows

- package.json
- packages/react-server/src/plugin/utils.tsx
- pnpm-lock.yaml
IDE showed red squiggles since they are already 5.8.3
> chore(deps): update typescript 5.8.3

- packages/react-server/examples/cloudflare/package.json
- packages/react-server/examples/custom-out-dir/package.json
- packages/react-server/examples/minimal/package.json
- packages/react-server/examples/next/package.json
- packages/react-server/examples/postcss-tailwind/package.json
- packages/react-server/examples/prerender/package.json
- packages/react-server/examples/starter/package.json
- packages/react-server/src/plugin/index.ts
- pnpm-lock.yaml
Some left over from https://github.com/hi-ogawa/vite-plugins/pull/854
> chore: cleanup vendored deps

- packages/react-server/CHANGELOG.md
- packages/react-server/package.json
- packages/rsc/CHANGELOG.md
- packages/rsc/package.json
Actually this is not a breaking change at all, so releasing it as patch.
> chore: release v0.3.1

- packages/rsc/examples/react-router/react-router-vite/entry.browser.tsx
- packages/rsc/examples/react-router/react-router-vite/entry.rsc.tsx
- packages/rsc/examples/react-router/react-router-vite/entry.ssr.tsx
- packages/rsc/src/browser.ts
- packages/rsc/src/extra/browser.tsx
- packages/rsc/src/extra/rsc.tsx
- packages/rsc/src/extra/ssr.tsx
- packages/rsc/src/rsc.tsx
- packages/rsc/src/ssr.tsx
looks silly but okay. the doc will look a bit nicer https://github.com/hi-ogawa/vite-plugins/pull/921
> feat(rsc): auto initialize

- packages/rsc/examples/basic/e2e/basic.test.ts
- packages/rsc/examples/react-router/e2e/basic.test.ts
- packages/rsc/src/plugin.ts
- extracted from https://github.com/hi-ogawa/vite-plugins/pull/926
> fix(rsc): emit assets manifest only in server build

- packages/react-server-next/src/vite/adapters/cloudflare/build.ts
- packages/react-server/examples/basic/misc/cf/build.js
- packages/react-server/examples/basic/vite.config.ts
- packages/react-server/src/plugin/index.ts
A bit scary but it's fine if CI passes.
> fix(react-server): inline react deps on ssr

- packages/transforms/package.json
- packages/transforms/src/hoist.ts
- packages/transforms/src/proxy-export.ts
- packages/transforms/src/server-action.ts
- packages/transforms/src/test-utils.ts
- packages/transforms/src/utils.ts
- packages/transforms/src/wrap-export.ts
- packages/transforms/tsconfig.json
- packages/transforms/tsdown.config.ts
- packages/transforms/tsup.config.ts
> chore: use tsdown in `packages/transforms`

- packages/rsc/examples/starter-cf-single/src/framework/entry.rsc.tsx
- packages/rsc/examples/starter-cf-single/src/framework/entry.ssr.tsx
- packages/rsc/examples/starter/src/framework/entry.rsc.tsx
- packages/rsc/examples/starter/src/framework/entry.ssr.tsx
- packages/rsc/src/extra/rsc.tsx
- packages/rsc/src/extra/ssr.tsx
> refactor: tweak `renderHtml` types and naming

- packages/rsc/src/plugin.ts
I just realized we can do this to avoid unnecessary chunk.
```js
$ pnpm -C packages/rsc/examples/react-router build
...
vite v6.3.5 building SSR bundle for production...
✓ 65 modules transformed.
dist/rsc/assets/home-CEW-mpAo.css                       0.05 kB
dist/rsc/assets/root-D_8-vVmz.css                      30.10 kB
dist/rsc/assets/about-DD2FU-8s.js                       0.27 kB
dist/rsc/assets/home.actions-DMkDcWrL.js                0.37 kB
dist/rsc/assets/home-DuiB34mx.js                        3.53 kB
dist/rsc/assets/root-CUGlExtB.js                        5.39 kB
dist/rsc/assets/jsx-runtime.react-server-BDq-Hq70.js   15.20 kB
dist/rsc/index.js                                     542.53 kB
✓ built in 417ms
```
```js
vite v6.3.5 building SSR bundle for production...
✓ 65 modules …
```
> fix: use static import for `loadCss` virtuals during build

- packages/rsc/README.md
- packages/rsc/examples/basic/vite.config.ts
- packages/rsc/src/plugin.ts
- packages/rsc/src/rsc.tsx
- packages/rsc/src/types/virtual.d.ts
- packages/rsc/src/utils/encryption-runtime.ts
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1068
Also moved some code to `encryption-runtime.ts` as pure refactoring.
> fix: stabilize server build by externalizing encryption key file

- packages/rsc/src/plugin.ts
This might help debugging issues like 
- https://github.com/remix-run/react-router/issues/13882
> feat: add `enableActionEncryption`

- packages/rsc/CHANGELOG.md
- packages/rsc/package.json
need a quick release since `starter` is broken
> chore: release v0.4.8

- packages/error-overlay/package.json
- packages/pre-bundle-new-url/package.json
- packages/react-server-next/package.json
- packages/react-server/package.json
- packages/rsc-react-router/package.json
- packages/rsc/package.json
- packages/server-asset/package.json
- packages/ssr-css/package.json
- packages/transforms/package.json
- packages/vite-import-dev-server/package.json
- packages/vite-null-export/package.json
- packages/vite-plugin-simple-hmr/package.json
- packages/vite-plugin-ssr-middleware/package.json
> chore: fix publint warning

- packages/fullstack/README.md
- packages/fullstack/examples/basic/.gitignore
- packages/fullstack/examples/basic/README.md
- packages/fullstack/examples/basic/package.json
- packages/fullstack/examples/basic/tsconfig.json
- packages/fullstack/examples/cloudflare/.gitignore
- packages/fullstack/examples/cloudflare/package.json
- packages/fullstack/examples/cloudflare/tsconfig.json
- packages/fullstack/examples/island/.gitignore
- packages/fullstack/examples/island/package.json
- packages/fullstack/examples/island/tsconfig.json
- packages/fullstack/examples/react-router/.gitignore
- packages/fullstack/examples/react-router/README.md
- packages/fullstack/examples/react-router/package.json
- packages/fullstack/examples/react-router/tsconfig.json
- packages/fullstack/examples/vue-router/.gitignore
- packages/fullstack/examples/vue-router/README.md
- packages/fullstack/examples/vue-router/package.json
- packages/fullstack/examples/vue-router/src/framework/entry.server.tsx
- packages/fullstack/examples/vue-router/tsconfig.json
- pnpm-lock.yaml
- closes https://github.com/hi-ogawa/vite-plugins/issues/1178
> chore(fullstack): standalone examples

- packages/fullstack/README.md
- packages/fullstack/examples/basic/src/entry.server.tsx
- packages/fullstack/examples/cloudflare/src/entry.server.tsx
- packages/fullstack/examples/island/src/entry.server.tsx
- packages/fullstack/examples/island/vite.config.ts
- packages/fullstack/examples/react-router/src/routes.ts
- packages/fullstack/examples/vue-router/src/routes.ts
- packages/fullstack/package.json
- packages/fullstack/src/plugin.ts
- pnpm-lock.yaml
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1189
The change is explained in an updated README.md.
> feat(fullstack)!: universal route assets as default

- packages/fullstack/examples/vue-router/src/framework/entry.client.tsx
- packages/fullstack/examples/vue-router/src/framework/entry.server.tsx
- packages/fullstack/examples/vue-router/src/root.vue
- packages/fullstack/examples/vue-router/src/routes.ts
- packages/fullstack/examples/vue-router/src/types.d.ts
Trying to learn from Nuxt https://github.com/nuxt/nuxt/blob/766806c8d90015873f86c3f103b09803bd214258/packages/nuxt/src/pages/runtime/plugins/router.ts
> chore(fullstack): tweak vue-router example

- packages/fullstack/examples/basic/src/entry.server.tsx
- packages/fullstack/examples/cloudflare/src/entry.server.tsx
- packages/fullstack/examples/island/src/entry.server.tsx
- packages/fullstack/examples/react-router/src/framework/entry.server.tsx
- packages/fullstack/examples/vue-router/src/framework/entry.server.ts
- packages/fullstack/src/plugin.ts
- packages/fullstack/types/query.d.ts
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1213
> feat(fullstack): support `?assets=client` and `?assets=ssr`

- packages/fullstack/src/plugin.ts
- Reviving https://github.com/hi-ogawa/vite-plugins/pull/1212 with an option to disable
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1226
The idea is that it's now easy to call `import("...?assets")` only for required modules. If they explicitly call it to get assets from that specific module, it's fine and natural to ensure css is collected properly. It would be nice to explain this behavior (essentially "how it works" in the doc).
Adding opt-out flag to allow checking behavior for quick testing.
> fix(fullstack): ensure module is analyzed during `collectCss`

- packages/fullstack/src/plugin.ts
I forgot to push one commit to https://github.com/hi-ogawa/vite-plugins/pull/1227
> fix(fullstack): rename options

- packages/fullstack/examples/island/src/framework/entry.server.tsx
- packages/fullstack/types/query.d.ts
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1232
It was just a typo :facepalm:
> fix(fullstack): fix `?assets` dts typing

- packages/fullstack/examples/island/src/framework/entry.server.tsx
- packages/fullstack/src/plugin.ts
- Closes https://github.com/hi-ogawa/vite-plugins/issues/1241
Oops, this is classic :facepalm:
> fix(fullstack): fix `collectCss` not traversing module due to non awaited promise
